In [1]:
import os
import ray
import numpy as np
import pandas as pd
from typing import List
from utils.data import load_yaml
from parsers.surface_track_id_parser import SurfaceObjectTrackParserDistributed
from imaris.imaris import ImarisDataObject

In [2]:
config_path = "config/config.yaml"
config = load_yaml(config_path)
config

{'data_dir': ['/home/shehan/Documents/projects/nih/nih_parsers/data/temp_test'],
 'save_dir': ['/home/shehan/Documents/projects/nih/nih_parsers/data/temp_test'],
 'valid_surfaces': -1,
 'cpu_cores': 12}

In [3]:
ims_file = "/home/shehan/Documents/projects/nih/nih_parsers/data/temp_test/Ex112-mitotrackerred-B6-BALB-050125_batch_TileScan_1_BALB-US-Position_3_(0).ims"

In [4]:
ims_object = ImarisDataObject(ims_file)
data = ims_object.data

In [5]:
data["Scene8"]["Content"]["MegaSurfaces0"].keys()

<KeysViewHDF5 ['BlockData', 'BlockInfo', 'BlockPath', 'Category', 'CategoryFunction', 'CreationParameters', 'Factor', 'FactorFunction', 'FactorList', 'FactorListFunction', 'LabelColor', 'LabelColorData', 'LabelColorLabelGroupNames', 'LabelColorLabelValues', 'LabelGroupNames', 'LabelSetLabelIDs', 'LabelSetObjectIDs', 'LabelSets', 'LabelValues', 'LevelInfo', 'MainTrackSegmentTable', 'MainTrackSegmentTable_Focus', 'MainTrackTable', 'SplitOffset', 'StatisticsType', 'StatisticsTypeFunction', 'StatisticsValue', 'StatisticsValueFunction', 'StatisticsValueTimeOffset', 'StatisticsValueTimeOffsetFunction', 'SurfaceModel', 'SurfaceModel2DInfo', 'SurfaceModelInfo', 'SurfaceTimeOffset', 'Time', 'TimeBegin', 'Track0', 'TrackEdge0', 'TrackObject0', 'TrackSegment0', 'TrackSegment0_Focus']>

In [6]:
parser = SurfaceObjectTrackParserDistributed(ims_file)

In [7]:
out = parser.inspect(0)

In [9]:
print(f"all surface names: {parser.surface_names}")
print(f"surface name: {out["surface_name"]}")
print(list(out.keys()))

all surface names: ['MegaSurfaces0']
surface name: MegaSurfaces0
['surface_name', 'stat_names_raw', 'stat_values_raw', 'object_id', 'factor', 'stat_names_channel_info', 'stat_names_surface_info', 'stat_values_filtered', 'organized_stats', 'stats_df', 'final_df']

In [16]:
stats_df = out["stats_df"]
database = out["final_df"]
track_info = parser.track_info.get(0)
object_info = parser.object_info.get(0)

In [17]:
database

,Acceleration,Acceleration X,Acceleration Y,Acceleration Z,Area,BoundingBoxAA Length X,BoundingBoxAA Length Y,BoundingBoxAA Length Z,BoundingBoxOO Length A,BoundingBoxOO Length B,...,Time Since Track Start,Velocity Angle X,Velocity Angle Y,Velocity Angle Z,Velocity X,Velocity Y,Velocity Z,Volume,Object_ID,Track_ID
0,0.000000,0.000000,0.000000,0.000000,2612.532959,41.707489,31.091003,15.998888,14.792021,30.354095,...,0.0,115.730408,73.730881,148.896225,-0.136261,0.087952,-0.268763,6740.480957,0,1.000000e+09
1,0.000000,0.000000,0.000000,0.000000,614.430847,15.166351,14.407990,13.999027,14.607727,15.557465,...,0.0,73.654175,17.273527,84.577354,1.554016,5.272064,0.521990,1032.898804,1,1.000000e+09
2,NaN,NaN,NaN,NaN,595.933167,14.408051,15.166306,13.999027,13.209564,13.857574,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1083.411377,2,NaN
3,0.000000,0.000000,0.000000,0.000000,909.628601,13.649719,21.232864,13.999027,13.293793,14.529671,...,0.0,52.122349,38.067715,86.773430,2.964966,3.801804,0.272010,2185.329102,3,1.000000e+09
4,0.000000,0.000000,0.000000,0.000000,603.822021,13.649719,13.649704,13.999027,12.407135,13.171967,...,0.0,58.979187,129.567520,124.986053,0.738525,-0.912720,-0.821565,1312.139893,4,1.000000e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32440,8.411903,-0.619156,-8.360657,0.690062,3.143441,3.033279,2.274948,3.999722,0.991871,1.032562,...,1.0,138.958405,130.605240,84.977478,-1.002892,-0.865402,0.116475,0.281079,32440,1.000028e+09
32441,14.271921,2.916595,-10.283104,9.457218,16.039974,3.033264,6.066536,3.999722,1.663489,2.476746,...,2.0,115.543518,100.650925,27.974693,-0.155563,-0.066669,0.318659,2.889613,32441,1.000030e+09
32442,10.697466,-5.497772,-5.976265,6.963802,1.417993,3.033264,2.274948,3.999722,0.569454,0.655510,...,4.0,138.119354,76.449181,128.697266,-1.864182,0.586796,-1.565367,0.097615,32442,1.000030e+09
32443,2.748623,-1.244181,-1.651446,1.810985,2.237356,2.274963,3.791588,3.999722,0.187986,0.939240,...,6.0,15.466559,74.690781,92.132759,2.736959,0.749891,-0.105548,0.092679,32443,1.000030e+09
32444,4.155824,-2.791911,-1.941360,-2.388980,36.336040,6.066544,3.033279,5.999583,2.220337,3.004303,...,4.0,70.732353,118.229767,35.220665,0.306905,-0.439835,0.759737,14.756499,32444,1.000031e+09

In [18]:
# how many unique object ids
print(len(stats_df["Object_ID"].unique()))
print(len(object_info["ID_Object"].unique()))

31427
31075

In [19]:
track_info

,ID,IndexTrackObjectBegin,IndexTrackObjectEnd,IndexTrackEdgeBegin,IndexTrackEdgeEnd
0,1000000000,0,51,0,50
1,1000000001,51,155,50,153
2,1000000003,155,247,153,244
3,1000000004,247,361,244,357
4,1000000005,361,480,357,475
...,...,...,...,...,...
606,1000031677,31062,31064,30456,30457
607,1000031715,31064,31067,30457,30459
608,1000031744,31067,31070,30459,30461
609,1000031815,31070,31073,30461,30463
610,1000031961,31073,31075,30463,30464

In [20]:
object_info[13]

KeyError: 13

In [34]:
rev_object_info = {v:k for k,v in object_info.to_dict()["ID_Object"].items()}

In [37]:
rev_object_info

{0: 0,
 351: 1,
 547: 2,
 808: 3,
 1074: 4,
 1338: 5,
 1610: 6,
 1893: 7,
 2156: 8,
 2431: 9,
 2697: 10,
 2980: 11,
 3325: 12,
 3588: 13,
 3789: 14,
 4057: 15,
 4328: 16,
 4607: 17,
 4881: 18,
 5166: 19,
 5509: 20,
 5704: 21,
 5972: 22,
 6249: 23,
 6526: 24,
 6805: 25,
 7078: 26,
 7342: 27,
 7624: 28,
 7901: 29,
 8253: 30,
 8450: 31,
 8798: 32,
 8999: 33,
 9357: 34,
 9626: 35,
 9899: 36,
 10097: 37,
 10386: 38,
 10667: 39,
 11005: 40,
 11214: 41,
 11486: 42,
 11760: 43,
 12039: 44,
 12583: 45,
 12857: 46,
 13126: 47,
 13393: 48,
 13658: 49,
 13919: 50,
 1: 51,
 265: 52,
 546: 53,
 809: 54,
 1075: 55,
 1340: 56,
 1609: 57,
 1880: 58,
 2155: 59,
 2435: 60,
 2780: 61,
 2976: 62,
 3326: 63,
 3587: 64,
 3787: 65,
 4058: 66,
 4326: 67,
 4603: 68,
 4878: 69,
 5162: 70,
 5427: 71,
 6050: 72,
 6244: 73,
 6522: 74,
 7344: 75,
 8178: 76,
 8453: 77,
 8720: 78,
 9280: 79,
 9559: 80,
 9829: 81,
 10100: 82,
 10379: 83,
 10656: 84,
 10936: 85,
 11213: 86,
 11556: 87,
 11750: 88,
 12029: 89,
 12304: 90,
 12570: 91,
 12914: 92,
 13123: 93,
 13384: 94,
 13728: 95,
 13982: 96,
 14250: 97,
 14438: 98,
 14779: 99,
 15024: 100,
 15303: 101,
 15489: 102,
 15745: 103,
 16537: 104,
 16801: 105,
 17329: 106,
 17597: 107,
 17933: 108,
 18472: 109,
 18656: 110,
 19278: 111,
 19550: 112,
 19746: 113,
 20074: 114,
 20337: 115,
 21137: 116,
 21353: 117,
 21697: 118,
 21956: 119,
 22147: 120,
 22493: 121,
 22768: 122,
 22969: 123,
 23224: 124,
 23493: 125,
 23837: 126,
 24033: 127,
 24369: 128,
 24646: 129,
 24917: 130,
 25182: 131,
 25441: 132,
 25714: 133,
 25988: 134,
 26189: 135,
 26521: 136,
 26714: 137,
 27267: 138,
 27542: 139,
 27799: 140,
 28083: 141,
 28351: 142,
 28617: 143,
 28875: 144,
 29143: 145,
 29413: 146,
 29680: 147,
 29942: 148,
 30211: 149,
 30468: 150,
 30753: 151,
 31024: 152,
 31307: 153,
 31825: 154,
 3: 155,
 266: 156,
 549: 157,
 811: 158,
 1076: 159,
 1341: 160,
 1611: 161,
 1881: 162,
 2157: 163,
 2429: 164,
 2698: 165,
 2977: 166,
 3328: 167,
 3590: 168,
 3788: 169,
 4060: 170,
 4330: 171,
 4605: 172,
 4880: 173,
 5163: 174,
 5428: 175,
 5702: 176,
 5973: 177,
 6246: 178,
 6525: 179,
 6807: 180,
 7075: 181,
 7345: 182,
 7621: 183,
 7903: 184,
 8176: 185,
 8451: 186,
 8718: 187,
 9003: 188,
 9276: 189,
 9628: 190,
 9821: 191,
 10099: 192,
 10451: 193,
 10653: 194,
 10926: 195,
 11201: 196,
 11552: 197,
 11829: 198,
 12027: 199,
 12378: 200,
 12648: 201,
 12912: 202,
 13111: 203,
 13383: 204,
 13645: 205,
 13981: 206,
 14253: 207,
 14516: 208,
 14778: 209,
 15029: 210,
 15300: 211,
 15558: 212,
 15744: 213,
 16094: 214,
 16351: 215,
 16529: 216,
 16790: 217,
 17126: 218,
 17394: 219,
 17664: 220,
 17932: 221,
 18203: 222,
 18471: 223,
 18657: 224,
 19005: 225,
 19549: 226,
 19808: 227,
 20328: 228,
 20609: 229,
 20880: 230,
 21132: 231,
 21427: 232,
 21698: 233,
 21953: 234,
 22215: 235,
 22495: 236,
 22767: 237,
 22961: 238,
 23222: 239,
 23569: 240,
 23760: 241,
 24371: 242,
 24648: 243,
 24914: 244,
 25108: 245,
 25444: 246,
 4: 247,
 267: 248,
 548: 249,
 810: 250,
 1077: 251,
 1342: 252,
 1612: 253,
 1882: 254,
 2159: 255,
 2428: 256,
 2699: 257,
 2978: 258,
 3327: 259,
 3589: 260,
 3790: 261,
 4059: 262,
 4329: 263,
 4604: 264,
 4879: 265,
 5164: 266,
 5429: 267,
 5703: 268,
 6051: 269,
 6247: 270,
 6523: 271,
 6808: 272,
 7076: 273,
 7346: 274,
 7622: 275,
 7902: 276,
 8179: 277,
 8455: 278,
 8721: 279,
 9004: 280,
 9277: 281,
 9552: 282,
 9822: 283,
 10102: 284,
 10371: 285,
 10657: 286,
 10929: 287,
 11203: 288,
 11555: 289,
 11752: 290,
 12031: 291,
 12305: 292,
 12571: 293,
 12915: 294,
 13117: 295,
 13385: 296,
 13647: 297,
 13984: 298,
 14175: 299,
 14441: 300,
 14781: 301,
 15031: 302,
 15559: 303,
 15746: 304,
 16012: 305,
 16268: 306,
 16530: 307,
 16792: 308,
 17129: 309,
 17397: 310,
 17666: 311,
 17936: 312,
 18204: 313,
 18474: 314,
 19280: 315,
 19552: 316,
 19810: 317,
 20071: 318,
 20334: 319,
 20611: 320,
 20881: 321,
 21135: 322,
 21429: 323,
 21618: 324,
 22496: 325,
 22765: 326,
 23040: 327,
 23223: 328,
 23570: 329,
 23840: 330,
 24036: 331,
 24373: 332,
 24573: 333,
 24915: 334,
 25184: 335,
 25368: 336,
 25709: 337,
 25987: 338,
 26258: 339,
 26519: 340,
 26787: 341,
 27057: 342,
 27258: 343,
 27530: 344,
 27872: 345,
 28155: 346,
 28607: 347,
 28949: 348,
 29222: 349,
 29477: 350,
 29676: 351,
 29939: 352,
 30202: 353,
 30541: 354,
 30748: 355,
 31094: 356,
 31296: 357,
 31550: 358,
 31827: 359,
 32160: 360,
 5: 361,
 271: 362,
 551: 363,
 814: 364,
 1079: 365,
 1344: 366,
 1615: 367,
 1887: 368,
 2162: 369,
 2436: 370,
 2705: 371,
 2984: 372,
 3253: 373,
 3519: 374,
 3795: 375,
 4064: 376,
 4334: 377,
 4611: 378,
 4887: 379,
 5161: 380,
 5433: 381,
 5707: 382,
 5976: 383,
 6245: 384,
 6521: 385,
 6811: 386,
 7080: 387,
 7347: 388,
 7626: 389,
 7906: 390,
 8180: 391,
 8454: 392,
 8725: 393,
 9006: 394,
 9281: 395,
 9557: 396,
 9828: 397,
 10101: 398,
 10375: 399,
 10655: 400,
 10927: 401,
 11209: 402,
 11553: 403,
 11830: 404,
 12030: 405,
 12309: 406,
 12573: 407,
 12844: 408,
 13115: 409,
 13388: 410,
 13649: 411,
 13909: 412,
 14179: 413,
 14439: 414,
 14703: 415,
 15034: 416,
 15224: 417,
 15491: 418,
 15750: 419,
 16017: 420,
 16274: 421,
 16535: 422,
 16799: 423,
 17130: 424,
 17326: 425,
 17592: 426,
 17860: 427,
 18132: 428,
 18399: 429,
 18663: 430,
 19009: 431,
 19206: 432,
 19551: 433,
 19743: 434,
 20002: 435,
 20333: 436,
 20536: 437,
 20809: 438,
 21143: 439,
 21630: 440,
 21885: 441,
 22222: 442,
 22499: 443,
 22686: 444,
 22964: 445,
 23225: 446,
 23488: 447,
 23766: 448,
 24035: 449,
 24374: 450,
 24578: 451,
 24840: 452,
 25109: 453,
 25370: 454,
 25641: 455,
 25993: 456,
 26192: 457,
 26454: 458,
 26715: 459,
 27058: 460,
 27264: 461,
 27538: 462,
 27873: 463,
 28076: 464,
 28344: 465,
 28610: 466,
 28948: 467,
 29139: 468,
 29405: 469,
 29677: 470,
 29940: 471,
 30203: 472,
 30542: 473,
 30749: 474,
 31023: 475,
 31300: 476,
 31551: 477,
 31821: 478,
 32086: 479,
 6: 480,
 268: 481,
 550: 482,
 812: 483,
 1078: 484,
 1343: 485,
 1613: 486,
 1884: 487,
 2158: 488,
 2430: 489,
 2700: 490,
 2979: 491,
 3249: 492,
 3591: 493,
 3791: 494,
 4061: 495,
 4331: 496,
 4606: 497,
 4882: 498,
 5165: 499,
 5430: 500,
 5705: 501,
 5971: 502,
 6248: 503,
 6524: 504,
 6809: 505,
 7077: 506,
 7348: 507,
 7623: 508,
 7904: 509,
 8181: 510,
 8456: 511,
 8722: 512,
 9005: 513,
 9278: 514,
 9553: 515,
 9823: 516,
 10103: 517,
 10372: 518,
 10658: 519,
 10930: 520,
 11204: 521,
 11475: 522,
 11751: 523,
 12032: 524,
 12306: 525,
 12572: 526,
 12916: 527,
 13116: 528,
 13386: 529,
 13648: 530,
 13985: 531,
 14176: 532,
 14440: 533,
 14698: 534,
 15032: 535,
 15222: 536,
 15481: 537,
 15747: 538,
 16013: 539,
 16269: 540,
 16531: 541,
 16793: 542,
 17050: 543,
 17398: 544,
 17667: 545,
 17853: 546,
 18205: 547,
 18475: 548,
 18659: 549,
 19007: 550,
 19282: 551,
 19553: 552,
 19812: 553,
 20073: 554,
 20335: 555,
 20612: 556,
 20803: 557,
 21136: 558,
 21430: 559,
 21620: 560,
 21959: 561,
 22208: 562,
 22497: 563,
 22770: 564,
 23041: 565,
 23226: 566,
 23572: 567,
 23762: 568,
 24037: 569,
 24375: 570,
 24574: 571,
 24916: 572,
 25110: 573,
 25369: 574,
 25713: 575,
 25994: 576,
 26187: 577,
 26452: 578,
 26716: 579,
 27062: 580,
 27260: 581,
 27533: 582,
 27797: 583,
 28074: 584,
 28343: 585,
 28609: 586,
 28872: 587,
 29141: 588,
 29406: 589,
 29679: 590,
 29941: 591,
 30204: 592,
 30464: 593,
 30750: 594,
 31099: 595,
 31298: 596,
 31552: 597,
 31824: 598,
 32085: 599,
 7: 600,
 270: 601,
 552: 602,
 813: 603,
 1080: 604,
 1345: 605,
 1614: 606,
 1885: 607,
 2160: 608,
 2432: 609,
 2701: 610,
 2981: 611,
 3250: 612,
 3516: 613,
 3792: 614,
 4062: 615,
 4332: 616,
 4608: 617,
 4884: 618,
 5167: 619,
 5431: 620,
 5706: 621,
 5974: 622,
 6250: 623,
 6528: 624,
 6810: 625,
 7079: 626,
 7349: 627,
 7625: 628,
 7905: 629,
 8182: 630,
 8457: 631,
 8723: 632,
 9000: 633,
 9279: 634,
 9554: 635,
 9825: 636,
 10104: 637,
 10373: 638,
 10659: 639,
 10931: 640,
 11205: 641,
 11476: 642,
 11753: 643,
 12034: 644,
 12307: 645,
 12576: 646,
 12845: 647,
 13118: 648,
 13387: 649,
 13650: 650,
 13986: 651,
 14178: 652,
 14442: 653,
 14699: 654,
 15033: 655,
 15225: 656,
 15482: 657,
 15748: 658,
 16014: 659,
 16270: 660,
 16532: 661,
 16794: 662,
 17051: 663,
 17399: 664,
 17668: 665,
 17854: 666,
 18128: 667,
 18397: 668,
 18661: 669,
 19008: 670,
 19283: 671,
 19476: 672,
 19811: 673,
 20075: 674,
 20336: 675,
 20613: 676,
 20804: 677,
 21139: 678,
 21431: 679,
 21621: 680,
 21880: 681,
 22219: 682,
 22498: 683,
 22685: 684,
 22962: 685,
 23227: 686,
 23489: 687,
 23763: 688,
 24038: 689,
 24297: 690,
 24575: 691,
 24841: 692,
 25111: 693,
 25371: 694,
 25717: 695,
 25916: 696,
 26188: 697,
 26453: 698,
 26717: 699,
 26987: 700,
 27261: 701,
 27534: 702,
 27798: 703,
 28077: 704,
 28346: 705,
 28611: 706,
 28947: 707,
 29142: 708,
 29407: 709,
 29678: 710,
 29945: 711,
 30205: 712,
 30544: 713,
 30752: 714,
 31020: 715,
 31303: 716,
 31553: 717,
 31823: 718,
 32084: 719,
 8: 720,
 275: 721,
 557: 722,
 820: 723,
 1084: 724,
 1348: 725,
 1621: 726,
 1892: 727,
 2166: 728,
 2702: 729,
 2988: 730,
 3255: 731,
 3521: 732,
 3799: 733,
 4069: 734,
 4614: 735,
 4886: 736,
 5174: 737,
 5436: 738,
 5713: 739,
 6532: 740,
 6815: 741,
 7086: 742,
 7350: 743,
 7630: 744,
 7909: 745,
 8187: 746,
 9: 747,
 269: 748,
 554: 749,
 815: 750,
 1081: 751,
 1347: 752,
 1616: 753,
 1886: 754,
 2161: 755,
 2433: 756,
 2704: 757,
 2982: 758,
 3251: 759,
 3517: 760,
 3793: 761,
 4063: 762,
 4333: 763,
 4609: 764,
 4883: 765,
 5168: 766,
 5434: 767,
 5708: 768,
 5977: 769,
 6251: 770,
 6527: 771,
 6812: 772,
 7081: 773,
 7351: 774,
 7627: 775,
 7907: 776,
 8183: 777,
 8458: 778,
 8724: 779,
 9007: 780,
 9282: 781,
 9556: 782,
 9827: 783,
 10105: 784,
 10377: 785,
 10660: 786,
 10932: 787,
 11208: 788,
 11479: 789,
 11755: 790,
 12036: 791,
 12310: 792,
 12578: 793,
 12848: 794,
 13121: 795,
 13390: 796,
 13653: 797,
 13910: 798,
 14181: 799,
 14445: 800,
 14702: 801,
 15036: 802,
 15227: 803,
 15486: 804,
 15752: 805,
 16019: 806,
 16272: 807,
 16533: 808,
 16795: 809,
 17052: 810,
 17400: 811,
 17591: 812,
 17856: 813,
 18130: 814,
 18398: 815,
 18660: 816,
 19011: 817,
 19205: 818,
 19477: 819,
 19813: 820,
 20077: 821,
 20338: 822,
 20615: 823,
 20805: 824,
 21138: 825,
 21432: 826,
 21622: 827,
 21881: 828,
 22220: 829,
 22500: 830,
 22688: 831,
 22963: 832,
 23228: 833,
 23491: 834,
 23764: 835,
 24039: 836,
 24300: 837,
 24577: 838,
 24842: 839,
 25112: 840,
 25372: 841,
 25637: 842,
 25918: 843,
 26191: 844,
 26455: 845,
 26718: 846,
 26990: 847,
 27262: 848,
 27536: 849,
 27801: 850,
 28079: 851,
 28348: 852,
 28613: 853,
 28874: 854,
 29145: 855,
 29408: 856,
 29682: 857,
 29943: 858,
 30207: 859,
 30465: 860,
 30754: 861,
 31022: 862,
 31302: 863,
 31555: 864,
 31828: 865,
 32088: 866,
 10: 867,
 274: 868,
 556: 869,
 817: 870,
 1082: 871,
 1350: 872,
 1620: 873,
 1891: 874,
 2163: 875,
 2437: 876,
 2708: 877,
 2985: 878,
 3257: 879,
 3522: 880,
 3800: 881,
 4066: 882,
 4337: 883,
 4616: 884,
 4890: 885,
 5177: 886,
 5440: 887,
 5712: 888,
 5981: 889,
 6253: 890,
 6536: 891,
 6819: 892,
 7089: 893,
 7357: 894,
 7634: 895,
 7914: 896,
 8188: 897,
 8461: 898,
 8728: 899,
 9011: 900,
 9561: 901,
 9832: 902,
 10110: 903,
 10382: 904,
 10938: 905,
 11218: 906,
 11482: 907,
 11757: 908,
 12040: 909,
 12315: 910,
 12584: 911,
 12854: 912,
 13125: 913,
 13394: 914,
 13657: 915,
 13917: 916,
 14185: 917,
 14449: 918,
 14708: 919,
 14965: 920,
 15232: 921,
 15492: 922,
 15758: 923,
 16023: 924,
 16278: 925,
 16540: 926,
 16803: 927,
 17058: 928,
 17331: 929,
 17599: 930,
 17864: 931,
 18136: 932,
 18404: 933,
 18668: 934,
 18937: 935,
 19483: 936,
 19748: 937,
 20005: 938,
 20270: 939,
 20541: 940,
 20815: 941,
 21071: 942,
 21357: 943,
 21626: 944,
 21889: 945,
 22151: 946,
 22429: 947,
 22695: 948,
 22971: 949,
 23231: 950,
 23497: 951,
 23770: 952,
 24044: 953,
 24305: 954,
 24583: 955,
 24851: 956,
 25118: 957,
 25377: 958,
 25643: 959,
 25924: 960,
 26196: 961,
 26462: 962,
 26723: 963,
 26996: 964,
 27270: 965,
 27544: 966,
 27806: 967,
 28086: 968,
 28352: 969,
 28618: 970,
 28879: 971,
 29149: 972,
 29412: 973,
 29685: 974,
 29950: 975,
 30213: 976,
 30472: 977,
 30759: 978,
 31028: 979,
 31304: 980,
 31561: 981,
 31832: 982,
 32093: 983,
 11: 984,
 272: 985,
 553: 986,
 1346: 987,
 1617: 988,
 1888: 989,
 2164: 990,
 2434: 991,
 2703: 992,
 2983: 993,
 3252: 994,
 3518: 995,
 3796: 996,
 4065: 997,
 4335: 998,
 4610: 999,
 ...}

In [20]:
stats_df["Track_ID"] = stats_df.apply(
    func=lambda x: database[int(x["Object_ID"].item())],
    axis=1,
)

KeyError: 2

In [23]:
out["final_df"]

{np.int64(0): np.int64(1000000000),
 np.int64(351): np.int64(1000000000),
 np.int64(547): np.int64(1000000000),
 np.int64(808): np.int64(1000000000),
 np.int64(1074): np.int64(1000000000),
 np.int64(1338): np.int64(1000000000),
 np.int64(1610): np.int64(1000000000),
 np.int64(1893): np.int64(1000000000),
 np.int64(2156): np.int64(1000000000),
 np.int64(2431): np.int64(1000000000),
 np.int64(2697): np.int64(1000000000),
 np.int64(2980): np.int64(1000000000),
 np.int64(3325): np.int64(1000000000),
 np.int64(3588): np.int64(1000000000),
 np.int64(3789): np.int64(1000000000),
 np.int64(4057): np.int64(1000000000),
 np.int64(4328): np.int64(1000000000),
 np.int64(4607): np.int64(1000000000),
 np.int64(4881): np.int64(1000000000),
 np.int64(5166): np.int64(1000000000),
 np.int64(5509): np.int64(1000000000),
 np.int64(5704): np.int64(1000000000),
 np.int64(5972): np.int64(1000000000),
 np.int64(6249): np.int64(1000000000),
 np.int64(6526): np.int64(1000000000),
 np.int64(6805): np.int64(1000000000),
 np.int64(7078): np.int64(1000000000),
 np.int64(7342): np.int64(1000000000),
 np.int64(7624): np.int64(1000000000),
 np.int64(7901): np.int64(1000000000),
 np.int64(8253): np.int64(1000000000),
 np.int64(8450): np.int64(1000000000),
 np.int64(8798): np.int64(1000000000),
 np.int64(8999): np.int64(1000000000),
 np.int64(9357): np.int64(1000000000),
 np.int64(9626): np.int64(1000000000),
 np.int64(9899): np.int64(1000000000),
 np.int64(10097): np.int64(1000000000),
 np.int64(10386): np.int64(1000000000),
 np.int64(10667): np.int64(1000000000),
 np.int64(11005): np.int64(1000000000),
 np.int64(11214): np.int64(1000000000),
 np.int64(11486): np.int64(1000000000),
 np.int64(11760): np.int64(1000000000),
 np.int64(12039): np.int64(1000000000),
 np.int64(12583): np.int64(1000000000),
 np.int64(12857): np.int64(1000000000),
 np.int64(13126): np.int64(1000000000),
 np.int64(13393): np.int64(1000000000),
 np.int64(13658): np.int64(1000000000),
 np.int64(13919): np.int64(1000000000),
 np.int64(1): np.int64(1000000001),
 np.int64(265): np.int64(1000000001),
 np.int64(546): np.int64(1000000001),
 np.int64(809): np.int64(1000000001),
 np.int64(1075): np.int64(1000000001),
 np.int64(1340): np.int64(1000000001),
 np.int64(1609): np.int64(1000000001),
 np.int64(1880): np.int64(1000000001),
 np.int64(2155): np.int64(1000000001),
 np.int64(2435): np.int64(1000000001),
 np.int64(2780): np.int64(1000000001),
 np.int64(2976): np.int64(1000000001),
 np.int64(3326): np.int64(1000000001),
 np.int64(3587): np.int64(1000000001),
 np.int64(3787): np.int64(1000000001),
 np.int64(4058): np.int64(1000000001),
 np.int64(4326): np.int64(1000000001),
 np.int64(4603): np.int64(1000000001),
 np.int64(4878): np.int64(1000000001),
 np.int64(5162): np.int64(1000000001),
 np.int64(5427): np.int64(1000000001),
 np.int64(6050): np.int64(1000000001),
 np.int64(6244): np.int64(1000000001),
 np.int64(6522): np.int64(1000000001),
 np.int64(7344): np.int64(1000000001),
 np.int64(8178): np.int64(1000000001),
 np.int64(8453): np.int64(1000000001),
 np.int64(8720): np.int64(1000000001),
 np.int64(9280): np.int64(1000000001),
 np.int64(9559): np.int64(1000000001),
 np.int64(9829): np.int64(1000000001),
 np.int64(10100): np.int64(1000000001),
 np.int64(10379): np.int64(1000000001),
 np.int64(10656): np.int64(1000000001),
 np.int64(10936): np.int64(1000000001),
 np.int64(11213): np.int64(1000000001),
 np.int64(11556): np.int64(1000000001),
 np.int64(11750): np.int64(1000000001),
 np.int64(12029): np.int64(1000000001),
 np.int64(12304): np.int64(1000000001),
 np.int64(12570): np.int64(1000000001),
 np.int64(12914): np.int64(1000000001),
 np.int64(13123): np.int64(1000000001),
 np.int64(13384): np.int64(1000000001),
 np.int64(13728): np.int64(1000000001),
 np.int64(13982): np.int64(1000000001),
 np.int64(14250): np.int64(1000000001),
 np.int64(14438): np.int64(1000000001),
 np.int64(14779): np.int64(1000000001),
 np.int64(15024): np.int64(1000000001),
 np.int64(15303): np.int64(1000000001),
 np.int64(15489): np.int64(1000000001),
 np.int64(15745): np.int64(1000000001),
 np.int64(16537): np.int64(1000000001),
 np.int64(16801): np.int64(1000000001),
 np.int64(17329): np.int64(1000000001),
 np.int64(17597): np.int64(1000000001),
 np.int64(17933): np.int64(1000000001),
 np.int64(18472): np.int64(1000000001),
 np.int64(18656): np.int64(1000000001),
 np.int64(19278): np.int64(1000000001),
 np.int64(19550): np.int64(1000000001),
 np.int64(19746): np.int64(1000000001),
 np.int64(20074): np.int64(1000000001),
 np.int64(20337): np.int64(1000000001),
 np.int64(21137): np.int64(1000000001),
 np.int64(21353): np.int64(1000000001),
 np.int64(21697): np.int64(1000000001),
 np.int64(21956): np.int64(1000000001),
 np.int64(22147): np.int64(1000000001),
 np.int64(22493): np.int64(1000000001),
 np.int64(22768): np.int64(1000000001),
 np.int64(22969): np.int64(1000000001),
 np.int64(23224): np.int64(1000000001),
 np.int64(23493): np.int64(1000000001),
 np.int64(23837): np.int64(1000000001),
 np.int64(24033): np.int64(1000000001),
 np.int64(24369): np.int64(1000000001),
 np.int64(24646): np.int64(1000000001),
 np.int64(24917): np.int64(1000000001),
 np.int64(25182): np.int64(1000000001),
 np.int64(25441): np.int64(1000000001),
 np.int64(25714): np.int64(1000000001),
 np.int64(25988): np.int64(1000000001),
 np.int64(26189): np.int64(1000000001),
 np.int64(26521): np.int64(1000000001),
 np.int64(26714): np.int64(1000000001),
 np.int64(27267): np.int64(1000000001),
 np.int64(27542): np.int64(1000000001),
 np.int64(27799): np.int64(1000000001),
 np.int64(28083): np.int64(1000000001),
 np.int64(28351): np.int64(1000000001),
 np.int64(28617): np.int64(1000000001),
 np.int64(28875): np.int64(1000000001),
 np.int64(29143): np.int64(1000000001),
 np.int64(29413): np.int64(1000000001),
 np.int64(29680): np.int64(1000000001),
 np.int64(29942): np.int64(1000000001),
 np.int64(30211): np.int64(1000000001),
 np.int64(30468): np.int64(1000000001),
 np.int64(30753): np.int64(1000000001),
 np.int64(31024): np.int64(1000000001),
 np.int64(31307): np.int64(1000000001),
 np.int64(31825): np.int64(1000000001),
 np.int64(3): np.int64(1000000003),
 np.int64(266): np.int64(1000000003),
 np.int64(549): np.int64(1000000003),
 np.int64(811): np.int64(1000000003),
 np.int64(1076): np.int64(1000000003),
 np.int64(1341): np.int64(1000000003),
 np.int64(1611): np.int64(1000000003),
 np.int64(1881): np.int64(1000000003),
 np.int64(2157): np.int64(1000000003),
 np.int64(2429): np.int64(1000000003),
 np.int64(2698): np.int64(1000000003),
 np.int64(2977): np.int64(1000000003),
 np.int64(3328): np.int64(1000000003),
 np.int64(3590): np.int64(1000000003),
 np.int64(3788): np.int64(1000000003),
 np.int64(4060): np.int64(1000000003),
 np.int64(4330): np.int64(1000000003),
 np.int64(4605): np.int64(1000000003),
 np.int64(4880): np.int64(1000000003),
 np.int64(5163): np.int64(1000000003),
 np.int64(5428): np.int64(1000000003),
 np.int64(5702): np.int64(1000000003),
 np.int64(5973): np.int64(1000000003),
 np.int64(6246): np.int64(1000000003),
 np.int64(6525): np.int64(1000000003),
 np.int64(6807): np.int64(1000000003),
 np.int64(7075): np.int64(1000000003),
 np.int64(7345): np.int64(1000000003),
 np.int64(7621): np.int64(1000000003),
 np.int64(7903): np.int64(1000000003),
 np.int64(8176): np.int64(1000000003),
 np.int64(8451): np.int64(1000000003),
 np.int64(8718): np.int64(1000000003),
 np.int64(9003): np.int64(1000000003),
 np.int64(9276): np.int64(1000000003),
 np.int64(9628): np.int64(1000000003),
 np.int64(9821): np.int64(1000000003),
 np.int64(10099): np.int64(1000000003),
 np.int64(10451): np.int64(1000000003),
 np.int64(10653): np.int64(1000000003),
 np.int64(10926): np.int64(1000000003),
 np.int64(11201): np.int64(1000000003),
 np.int64(11552): np.int64(1000000003),
 np.int64(11829): np.int64(1000000003),
 np.int64(12027): np.int64(1000000003),
 np.int64(12378): np.int64(1000000003),
 np.int64(12648): np.int64(1000000003),
 np.int64(12912): np.int64(1000000003),
 np.int64(13111): np.int64(1000000003),
 np.int64(13383): np.int64(1000000003),
 np.int64(13645): np.int64(1000000003),
 np.int64(13981): np.int64(1000000003),
 np.int64(14253): np.int64(1000000003),
 np.int64(14516): np.int64(1000000003),
 np.int64(14778): np.int64(1000000003),
 np.int64(15029): np.int64(1000000003),
 np.int64(15300): np.int64(1000000003),
 np.int64(15558): np.int64(1000000003),
 np.int64(15744): np.int64(1000000003),
 np.int64(16094): np.int64(1000000003),
 np.int64(16351): np.int64(1000000003),
 np.int64(16529): np.int64(1000000003),
 np.int64(16790): np.int64(1000000003),
 np.int64(17126): np.int64(1000000003),
 np.int64(17394): np.int64(1000000003),
 np.int64(17664): np.int64(1000000003),
 np.int64(17932): np.int64(1000000003),
 np.int64(18203): np.int64(1000000003),
 np.int64(18471): np.int64(1000000003),
 np.int64(18657): np.int64(1000000003),
 np.int64(19005): np.int64(1000000003),
 np.int64(19549): np.int64(1000000003),
 np.int64(19808): np.int64(1000000003),
 np.int64(20328): np.int64(1000000003),
 np.int64(20609): np.int64(1000000003),
 np.int64(20880): np.int64(1000000003),
 np.int64(21132): np.int64(1000000003),
 np.int64(21427): np.int64(1000000003),
 np.int64(21698): np.int64(1000000003),
 np.int64(21953): np.int64(1000000003),
 np.int64(22215): np.int64(1000000003),
 np.int64(22495): np.int64(1000000003),
 np.int64(22767): np.int64(1000000003),
 np.int64(22961): np.int64(1000000003),
 np.int64(23222): np.int64(1000000003),
 np.int64(23569): np.int64(1000000003),
 np.int64(23760): np.int64(1000000003),
 np.int64(24371): np.int64(1000000003),
 np.int64(24648): np.int64(1000000003),
 np.int64(24914): np.int64(1000000003),
 np.int64(25108): np.int64(1000000003),
 np.int64(25444): np.int64(1000000003),
 np.int64(4): np.int64(1000000004),
 np.int64(267): np.int64(1000000004),
 np.int64(548): np.int64(1000000004),
 np.int64(810): np.int64(1000000004),
 np.int64(1077): np.int64(1000000004),
 np.int64(1342): np.int64(1000000004),
 np.int64(1612): np.int64(1000000004),
 np.int64(1882): np.int64(1000000004),
 np.int64(2159): np.int64(1000000004),
 np.int64(2428): np.int64(1000000004),
 np.int64(2699): np.int64(1000000004),
 np.int64(2978): np.int64(1000000004),
 np.int64(3327): np.int64(1000000004),
 np.int64(3589): np.int64(1000000004),
 np.int64(3790): np.int64(1000000004),
 np.int64(4059): np.int64(1000000004),
 np.int64(4329): np.int64(1000000004),
 np.int64(4604): np.int64(1000000004),
 np.int64(4879): np.int64(1000000004),
 np.int64(5164): np.int64(1000000004),
 np.int64(5429): np.int64(1000000004),
 np.int64(5703): np.int64(1000000004),
 np.int64(6051): np.int64(1000000004),
 np.int64(6247): np.int64(1000000004),
 np.int64(6523): np.int64(1000000004),
 np.int64(6808): np.int64(1000000004),
 np.int64(7076): np.int64(1000000004),
 np.int64(7346): np.int64(1000000004),
 np.int64(7622): np.int64(1000000004),
 np.int64(7902): np.int64(1000000004),
 np.int64(8179): np.int64(1000000004),
 np.int64(8455): np.int64(1000000004),
 np.int64(8721): np.int64(1000000004),
 np.int64(9004): np.int64(1000000004),
 np.int64(9277): np.int64(1000000004),
 np.int64(9552): np.int64(1000000004),
 np.int64(9822): np.int64(1000000004),
 np.int64(10102): np.int64(1000000004),
 np.int64(10371): np.int64(1000000004),
 np.int64(10657): np.int64(1000000004),
 np.int64(10929): np.int64(1000000004),
 np.int64(11203): np.int64(1000000004),
 np.int64(11555): np.int64(1000000004),
 np.int64(11752): np.int64(1000000004),
 np.int64(12031): np.int64(1000000004),
 np.int64(12305): np.int64(1000000004),
 np.int64(12571): np.int64(1000000004),
 np.int64(12915): np.int64(1000000004),
 np.int64(13117): np.int64(1000000004),
 np.int64(13385): np.int64(1000000004),
 np.int64(13647): np.int64(1000000004),
 np.int64(13984): np.int64(1000000004),
 np.int64(14175): np.int64(1000000004),
 np.int64(14441): np.int64(1000000004),
 np.int64(14781): np.int64(1000000004),
 np.int64(15031): np.int64(1000000004),
 np.int64(15559): np.int64(1000000004),
 np.int64(15746): np.int64(1000000004),
 np.int64(16012): np.int64(1000000004),
 np.int64(16268): np.int64(1000000004),
 np.int64(16530): np.int64(1000000004),
 np.int64(16792): np.int64(1000000004),
 np.int64(17129): np.int64(1000000004),
 np.int64(17397): np.int64(1000000004),
 np.int64(17666): np.int64(1000000004),
 np.int64(17936): np.int64(1000000004),
 np.int64(18204): np.int64(1000000004),
 np.int64(18474): np.int64(1000000004),
 np.int64(19280): np.int64(1000000004),
 np.int64(19552): np.int64(1000000004),
 np.int64(19810): np.int64(1000000004),
 np.int64(20071): np.int64(1000000004),
 np.int64(20334): np.int64(1000000004),
 np.int64(20611): np.int64(1000000004),
 np.int64(20881): np.int64(1000000004),
 np.int64(21135): np.int64(1000000004),
 np.int64(21429): np.int64(1000000004),
 np.int64(21618): np.int64(1000000004),
 np.int64(22496): np.int64(1000000004),
 np.int64(22765): np.int64(1000000004),
 np.int64(23040): np.int64(1000000004),
 np.int64(23223): np.int64(1000000004),
 np.int64(23570): np.int64(1000000004),
 np.int64(23840): np.int64(1000000004),
 np.int64(24036): np.int64(1000000004),
 np.int64(24373): np.int64(1000000004),
 np.int64(24573): np.int64(1000000004),
 np.int64(24915): np.int64(1000000004),
 np.int64(25184): np.int64(1000000004),
 np.int64(25368): np.int64(1000000004),
 np.int64(25709): np.int64(1000000004),
 np.int64(25987): np.int64(1000000004),
 np.int64(26258): np.int64(1000000004),
 np.int64(26519): np.int64(1000000004),
 np.int64(26787): np.int64(1000000004),
 np.int64(27057): np.int64(1000000004),
 np.int64(27258): np.int64(1000000004),
 np.int64(27530): np.int64(1000000004),
 np.int64(27872): np.int64(1000000004),
 np.int64(28155): np.int64(1000000004),
 np.int64(28607): np.int64(1000000004),
 np.int64(28949): np.int64(1000000004),
 np.int64(29222): np.int64(1000000004),
 np.int64(29477): np.int64(1000000004),
 np.int64(29676): np.int64(1000000004),
 np.int64(29939): np.int64(1000000004),
 np.int64(30202): np.int64(1000000004),
 np.int64(30541): np.int64(1000000004),
 np.int64(30748): np.int64(1000000004),
 np.int64(31094): np.int64(1000000004),
 np.int64(31296): np.int64(1000000004),
 np.int64(31550): np.int64(1000000004),
 np.int64(31827): np.int64(1000000004),
 np.int64(32160): np.int64(1000000004),
 np.int64(5): np.int64(1000000005),
 np.int64(271): np.int64(1000000005),
 np.int64(551): np.int64(1000000005),
 np.int64(814): np.int64(1000000005),
 np.int64(1079): np.int64(1000000005),
 np.int64(1344): np.int64(1000000005),
 np.int64(1615): np.int64(1000000005),
 np.int64(1887): np.int64(1000000005),
 np.int64(2162): np.int64(1000000005),
 np.int64(2436): np.int64(1000000005),
 np.int64(2705): np.int64(1000000005),
 np.int64(2984): np.int64(1000000005),
 np.int64(3253): np.int64(1000000005),
 np.int64(3519): np.int64(1000000005),
 np.int64(3795): np.int64(1000000005),
 np.int64(4064): np.int64(1000000005),
 np.int64(4334): np.int64(1000000005),
 np.int64(4611): np.int64(1000000005),
 np.int64(4887): np.int64(1000000005),
 np.int64(5161): np.int64(1000000005),
 np.int64(5433): np.int64(1000000005),
 np.int64(5707): np.int64(1000000005),
 np.int64(5976): np.int64(1000000005),
 np.int64(6245): np.int64(1000000005),
 np.int64(6521): np.int64(1000000005),
 np.int64(6811): np.int64(1000000005),
 np.int64(7080): np.int64(1000000005),
 np.int64(7347): np.int64(1000000005),
 np.int64(7626): np.int64(1000000005),
 np.int64(7906): np.int64(1000000005),
 np.int64(8180): np.int64(1000000005),
 np.int64(8454): np.int64(1000000005),
 np.int64(8725): np.int64(1000000005),
 np.int64(9006): np.int64(1000000005),
 np.int64(9281): np.int64(1000000005),
 np.int64(9557): np.int64(1000000005),
 np.int64(9828): np.int64(1000000005),
 np.int64(10101): np.int64(1000000005),
 np.int64(10375): np.int64(1000000005),
 np.int64(10655): np.int64(1000000005),
 np.int64(10927): np.int64(1000000005),
 np.int64(11209): np.int64(1000000005),
 np.int64(11553): np.int64(1000000005),
 np.int64(11830): np.int64(1000000005),
 np.int64(12030): np.int64(1000000005),
 np.int64(12309): np.int64(1000000005),
 np.int64(12573): np.int64(1000000005),
 np.int64(12844): np.int64(1000000005),
 np.int64(13115): np.int64(1000000005),
 np.int64(13388): np.int64(1000000005),
 np.int64(13649): np.int64(1000000005),
 np.int64(13909): np.int64(1000000005),
 np.int64(14179): np.int64(1000000005),
 np.int64(14439): np.int64(1000000005),
 np.int64(14703): np.int64(1000000005),
 np.int64(15034): np.int64(1000000005),
 np.int64(15224): np.int64(1000000005),
 np.int64(15491): np.int64(1000000005),
 np.int64(15750): np.int64(1000000005),
 np.int64(16017): np.int64(1000000005),
 np.int64(16274): np.int64(1000000005),
 np.int64(16535): np.int64(1000000005),
 np.int64(16799): np.int64(1000000005),
 np.int64(17130): np.int64(1000000005),
 np.int64(17326): np.int64(1000000005),
 np.int64(17592): np.int64(1000000005),
 np.int64(17860): np.int64(1000000005),
 np.int64(18132): np.int64(1000000005),
 np.int64(18399): np.int64(1000000005),
 np.int64(18663): np.int64(1000000005),
 np.int64(19009): np.int64(1000000005),
 np.int64(19206): np.int64(1000000005),
 np.int64(19551): np.int64(1000000005),
 np.int64(19743): np.int64(1000000005),
 np.int64(20002): np.int64(1000000005),
 np.int64(20333): np.int64(1000000005),
 np.int64(20536): np.int64(1000000005),
 np.int64(20809): np.int64(1000000005),
 np.int64(21143): np.int64(1000000005),
 np.int64(21630): np.int64(1000000005),
 np.int64(21885): np.int64(1000000005),
 np.int64(22222): np.int64(1000000005),
 np.int64(22499): np.int64(1000000005),
 np.int64(22686): np.int64(1000000005),
 np.int64(22964): np.int64(1000000005),
 np.int64(23225): np.int64(1000000005),
 np.int64(23488): np.int64(1000000005),
 np.int64(23766): np.int64(1000000005),
 np.int64(24035): np.int64(1000000005),
 np.int64(24374): np.int64(1000000005),
 np.int64(24578): np.int64(1000000005),
 np.int64(24840): np.int64(1000000005),
 np.int64(25109): np.int64(1000000005),
 np.int64(25370): np.int64(1000000005),
 np.int64(25641): np.int64(1000000005),
 np.int64(25993): np.int64(1000000005),
 np.int64(26192): np.int64(1000000005),
 np.int64(26454): np.int64(1000000005),
 np.int64(26715): np.int64(1000000005),
 np.int64(27058): np.int64(1000000005),
 np.int64(27264): np.int64(1000000005),
 np.int64(27538): np.int64(1000000005),
 np.int64(27873): np.int64(1000000005),
 np.int64(28076): np.int64(1000000005),
 np.int64(28344): np.int64(1000000005),
 np.int64(28610): np.int64(1000000005),
 np.int64(28948): np.int64(1000000005),
 np.int64(29139): np.int64(1000000005),
 np.int64(29405): np.int64(1000000005),
 np.int64(29677): np.int64(1000000005),
 np.int64(29940): np.int64(1000000005),
 np.int64(30203): np.int64(1000000005),
 np.int64(30542): np.int64(1000000005),
 np.int64(30749): np.int64(1000000005),
 np.int64(31023): np.int64(1000000005),
 np.int64(31300): np.int64(1000000005),
 np.int64(31551): np.int64(1000000005),
 np.int64(31821): np.int64(1000000005),
 np.int64(32086): np.int64(1000000005),
 np.int64(6): np.int64(1000000006),
 np.int64(268): np.int64(1000000006),
 np.int64(550): np.int64(1000000006),
 np.int64(812): np.int64(1000000006),
 np.int64(1078): np.int64(1000000006),
 np.int64(1343): np.int64(1000000006),
 np.int64(1613): np.int64(1000000006),
 np.int64(1884): np.int64(1000000006),
 np.int64(2158): np.int64(1000000006),
 np.int64(2430): np.int64(1000000006),
 np.int64(2700): np.int64(1000000006),
 np.int64(2979): np.int64(1000000006),
 np.int64(3249): np.int64(1000000006),
 np.int64(3591): np.int64(1000000006),
 np.int64(3791): np.int64(1000000006),
 np.int64(4061): np.int64(1000000006),
 np.int64(4331): np.int64(1000000006),
 np.int64(4606): np.int64(1000000006),
 np.int64(4882): np.int64(1000000006),
 np.int64(5165): np.int64(1000000006),
 np.int64(5430): np.int64(1000000006),
 np.int64(5705): np.int64(1000000006),
 np.int64(5971): np.int64(1000000006),
 np.int64(6248): np.int64(1000000006),
 np.int64(6524): np.int64(1000000006),
 np.int64(6809): np.int64(1000000006),

In [35]:
sorted(object_info["ID_Object"].unique())

[np.int64(0),
 np.int64(1),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9),
 np.int64(10),
 np.int64(11),
 np.int64(12),
 np.int64(13),
 np.int64(14),
 np.int64(15),
 np.int64(16),
 np.int64(17),
 np.int64(18),
 np.int64(19),
 np.int64(20),
 np.int64(21),
 np.int64(22),
 np.int64(23),
 np.int64(24),
 np.int64(25),
 np.int64(26),
 np.int64(29),
 np.int64(30),
 np.int64(31),
 np.int64(33),
 np.int64(34),
 np.int64(35),
 np.int64(36),
 np.int64(37),
 np.int64(38),
 np.int64(39),
 np.int64(40),
 np.int64(41),
 np.int64(42),
 np.int64(43),
 np.int64(44),
 np.int64(45),
 np.int64(47),
 np.int64(48),
 np.int64(49),
 np.int64(50),
 np.int64(51),
 np.int64(53),
 np.int64(54),
 np.int64(55),
 np.int64(56),
 np.int64(57),
 np.int64(58),
 np.int64(59),
 np.int64(60),
 np.int64(61),
 np.int64(62),
 np.int64(63),
 np.int64(64),
 np.int64(65),
 np.int64(66),
 np.int64(67),
 np.int64(68),
 np.int64(70),
 np.int64(71),
 np.int64(72),
 np.int64(73),
 np.int64(74),
 np.int64(75),
 np.int64(76),
 np.int64(77),
 np.int64(78),
 np.int64(79),
 np.int64(80),
 np.int64(81),
 np.int64(82),
 np.int64(83),
 np.int64(84),
 np.int64(85),
 np.int64(87),
 np.int64(88),
 np.int64(89),
 np.int64(90),
 np.int64(91),
 np.int64(92),
 np.int64(94),
 np.int64(95),
 np.int64(96),
 np.int64(97),
 np.int64(98),
 np.int64(99),
 np.int64(100),
 np.int64(101),
 np.int64(102),
 np.int64(103),
 np.int64(104),
 np.int64(105),
 np.int64(106),
 np.int64(107),
 np.int64(108),
 np.int64(109),
 np.int64(110),
 np.int64(111),
 np.int64(112),
 np.int64(113),
 np.int64(114),
 np.int64(115),
 np.int64(116),
 np.int64(117),
 np.int64(118),
 np.int64(119),
 np.int64(120),
 np.int64(121),
 np.int64(122),
 np.int64(123),
 np.int64(124),
 np.int64(125),
 np.int64(126),
 np.int64(127),
 np.int64(128),
 np.int64(129),
 np.int64(130),
 np.int64(131),
 np.int64(132),
 np.int64(133),
 np.int64(134),
 np.int64(135),
 np.int64(136),
 np.int64(137),
 np.int64(138),
 np.int64(139),
 np.int64(140),
 np.int64(141),
 np.int64(142),
 np.int64(143),
 np.int64(144),
 np.int64(145),
 np.int64(146),
 np.int64(147),
 np.int64(148),
 np.int64(149),
 np.int64(150),
 np.int64(152),
 np.int64(153),
 np.int64(154),
 np.int64(155),
 np.int64(156),
 np.int64(157),
 np.int64(158),
 np.int64(159),
 np.int64(161),
 np.int64(162),
 np.int64(163),
 np.int64(164),
 np.int64(165),
 np.int64(166),
 np.int64(167),
 np.int64(168),
 np.int64(169),
 np.int64(170),
 np.int64(171),
 np.int64(172),
 np.int64(173),
 np.int64(174),
 np.int64(175),
 np.int64(176),
 np.int64(177),
 np.int64(178),
 np.int64(179),
 np.int64(180),
 np.int64(181),
 np.int64(182),
 np.int64(183),
 np.int64(184),
 np.int64(185),
 np.int64(186),
 np.int64(187),
 np.int64(188),
 np.int64(189),
 np.int64(190),
 np.int64(191),
 np.int64(192),
 np.int64(193),
 np.int64(195),
 np.int64(196),
 np.int64(197),
 np.int64(198),
 np.int64(199),
 np.int64(200),
 np.int64(201),
 np.int64(202),
 np.int64(203),
 np.int64(204),
 np.int64(205),
 np.int64(206),
 np.int64(207),
 np.int64(208),
 np.int64(209),
 np.int64(211),
 np.int64(212),
 np.int64(213),
 np.int64(214),
 np.int64(215),
 np.int64(216),
 np.int64(218),
 np.int64(219),
 np.int64(220),
 np.int64(221),
 np.int64(222),
 np.int64(223),
 np.int64(224),
 np.int64(225),
 np.int64(226),
 np.int64(227),
 np.int64(228),
 np.int64(229),
 np.int64(231),
 np.int64(232),
 np.int64(233),
 np.int64(234),
 np.int64(235),
 np.int64(236),
 np.int64(237),
 np.int64(238),
 np.int64(239),
 np.int64(240),
 np.int64(241),
 np.int64(242),
 np.int64(244),
 np.int64(245),
 np.int64(246),
 np.int64(247),
 np.int64(248),
 np.int64(249),
 np.int64(251),
 np.int64(252),
 np.int64(253),
 np.int64(254),
 np.int64(255),
 np.int64(256),
 np.int64(257),
 np.int64(258),
 np.int64(259),
 np.int64(260),
 np.int64(261),
 np.int64(262),
 np.int64(263),
 np.int64(264),
 np.int64(265),
 np.int64(266),
 np.int64(267),
 np.int64(268),
 np.int64(269),
 np.int64(270),
 np.int64(271),
 np.int64(272),
 np.int64(273),
 np.int64(274),
 np.int64(275),
 np.int64(276),
 np.int64(277),
 np.int64(278),
 np.int64(279),
 np.int64(280),
 np.int64(281),
 np.int64(282),
 np.int64(283),
 np.int64(284),
 np.int64(285),
 np.int64(286),
 np.int64(287),
 np.int64(288),
 np.int64(289),
 np.int64(290),
 np.int64(291),
 np.int64(293),
 np.int64(294),
 np.int64(296),
 np.int64(297),
 np.int64(298),
 np.int64(299),
 np.int64(300),
 np.int64(301),
 np.int64(302),
 np.int64(304),
 np.int64(305),
 np.int64(306),
 np.int64(307),
 np.int64(308),
 np.int64(309),
 np.int64(310),
 np.int64(311),
 np.int64(313),
 np.int64(314),
 np.int64(315),
 np.int64(316),
 np.int64(317),
 np.int64(318),
 np.int64(319),
 np.int64(320),
 np.int64(321),
 np.int64(322),
 np.int64(323),
 np.int64(324),
 np.int64(325),
 np.int64(326),
 np.int64(327),
 np.int64(328),
 np.int64(329),
 np.int64(330),
 np.int64(331),
 np.int64(332),
 np.int64(333),
 np.int64(334),
 np.int64(336),
 np.int64(337),
 np.int64(338),
 np.int64(339),
 np.int64(340),
 np.int64(341),
 np.int64(342),
 np.int64(343),
 np.int64(344),
 np.int64(345),
 np.int64(346),
 np.int64(347),
 np.int64(348),
 np.int64(349),
 np.int64(350),
 np.int64(351),
 np.int64(352),
 np.int64(353),
 np.int64(355),
 np.int64(356),
 np.int64(357),
 np.int64(358),
 np.int64(360),
 np.int64(361),
 np.int64(362),
 np.int64(364),
 np.int64(365),
 np.int64(366),
 np.int64(367),
 np.int64(368),
 np.int64(369),
 np.int64(370),
 np.int64(371),
 np.int64(372),
 np.int64(373),
 np.int64(374),
 np.int64(375),
 np.int64(376),
 np.int64(377),
 np.int64(378),
 np.int64(379),
 np.int64(380),
 np.int64(381),
 np.int64(382),
 np.int64(383),
 np.int64(385),
 np.int64(386),
 np.int64(387),
 np.int64(388),
 np.int64(389),
 np.int64(390),
 np.int64(392),
 np.int64(393),
 np.int64(394),
 np.int64(395),
 np.int64(396),
 np.int64(397),
 np.int64(398),
 np.int64(399),
 np.int64(400),
 np.int64(401),
 np.int64(402),
 np.int64(403),
 np.int64(404),
 np.int64(405),
 np.int64(406),
 np.int64(407),
 np.int64(408),
 np.int64(409),
 np.int64(410),
 np.int64(411),
 np.int64(412),
 np.int64(413),
 np.int64(414),
 np.int64(415),
 np.int64(416),
 np.int64(417),
 np.int64(418),
 np.int64(419),
 np.int64(420),
 np.int64(421),
 np.int64(422),
 np.int64(423),
 np.int64(424),
 np.int64(425),
 np.int64(426),
 np.int64(427),
 np.int64(428),
 np.int64(429),
 np.int64(430),
 np.int64(431),
 np.int64(432),
 np.int64(433),
 np.int64(434),
 np.int64(435),
 np.int64(436),
 np.int64(437),
 np.int64(438),
 np.int64(439),
 np.int64(440),
 np.int64(441),
 np.int64(442),
 np.int64(443),
 np.int64(444),
 np.int64(446),
 np.int64(447),
 np.int64(448),
 np.int64(449),
 np.int64(450),
 np.int64(451),
 np.int64(452),
 np.int64(453),
 np.int64(454),
 np.int64(456),
 np.int64(457),
 np.int64(458),
 np.int64(459),
 np.int64(460),
 np.int64(461),
 np.int64(462),
 np.int64(463),
 np.int64(464),
 np.int64(465),
 np.int64(466),
 np.int64(467),
 np.int64(468),
 np.int64(469),
 np.int64(470),
 np.int64(471),
 np.int64(472),
 np.int64(473),
 np.int64(474),
 np.int64(475),
 np.int64(476),
 np.int64(477),
 np.int64(478),
 np.int64(479),
 np.int64(480),
 np.int64(481),
 np.int64(482),
 np.int64(483),
 np.int64(484),
 np.int64(485),
 np.int64(486),
 np.int64(487),
 np.int64(488),
 np.int64(489),
 np.int64(490),
 np.int64(491),
 np.int64(492),
 np.int64(493),
 np.int64(494),
 np.int64(495),
 np.int64(496),
 np.int64(497),
 np.int64(498),
 np.int64(499),
 np.int64(500),
 np.int64(501),
 np.int64(502),
 np.int64(503),
 np.int64(504),
 np.int64(506),
 np.int64(507),
 np.int64(508),
 np.int64(509),
 np.int64(510),
 np.int64(511),
 np.int64(512),
 np.int64(513),
 np.int64(514),
 np.int64(515),
 np.int64(516),
 np.int64(517),
 np.int64(518),
 np.int64(519),
 np.int64(520),
 np.int64(521),
 np.int64(522),
 np.int64(523),
 np.int64(524),
 np.int64(525),
 np.int64(526),
 np.int64(527),
 np.int64(528),
 np.int64(529),
 np.int64(530),
 np.int64(531),
 np.int64(532),
 np.int64(533),
 np.int64(534),
 np.int64(535),
 np.int64(536),
 np.int64(537),
 np.int64(538),
 np.int64(539),
 np.int64(540),
 np.int64(541),
 np.int64(542),
 np.int64(543),
 np.int64(544),
 np.int64(545),
 np.int64(546),
 np.int64(547),
 np.int64(548),
 np.int64(549),
 np.int64(550),
 np.int64(551),
 np.int64(552),
 np.int64(553),
 np.int64(554),
 np.int64(555),
 np.int64(556),
 np.int64(557),
 np.int64(558),
 np.int64(559),
 np.int64(560),
 np.int64(561),
 np.int64(562),
 np.int64(563),
 np.int64(564),
 np.int64(565),
 np.int64(566),
 np.int64(567),
 np.int64(568),
 np.int64(569),
 np.int64(570),
 np.int64(571),
 np.int64(572),
 np.int64(573),
 np.int64(574),
 np.int64(575),
 np.int64(576),
 np.int64(577),
 np.int64(578),
 np.int64(579),
 np.int64(580),
 np.int64(581),
 np.int64(582),
 np.int64(583),
 np.int64(584),
 np.int64(585),
 np.int64(586),
 np.int64(587),
 np.int64(588),
 np.int64(589),
 np.int64(590),
 np.int64(591),
 np.int64(592),
 np.int64(593),
 np.int64(594),
 np.int64(595),
 np.int64(597),
 np.int64(598),
 np.int64(599),
 np.int64(600),
 np.int64(601),
 np.int64(602),
 np.int64(603),
 np.int64(604),
 np.int64(605),
 np.int64(606),
 np.int64(607),
 np.int64(608),
 np.int64(609),
 np.int64(610),
 np.int64(611),
 np.int64(612),
 np.int64(613),
 np.int64(614),
 np.int64(615),
 np.int64(616),
 np.int64(617),
 np.int64(618),
 np.int64(619),
 np.int64(620),
 np.int64(621),
 np.int64(622),
 np.int64(623),
 np.int64(624),
 np.int64(625),
 np.int64(626),
 np.int64(627),
 np.int64(628),
 np.int64(629),
 np.int64(630),
 np.int64(631),
 np.int64(632),
 np.int64(633),
 np.int64(634),
 np.int64(635),
 np.int64(636),
 np.int64(637),
 np.int64(638),
 np.int64(639),
 np.int64(640),
 np.int64(641),
 np.int64(642),
 np.int64(643),
 np.int64(644),
 np.int64(645),
 np.int64(646),
 np.int64(647),
 np.int64(648),
 np.int64(649),
 np.int64(650),
 np.int64(651),
 np.int64(652),
 np.int64(653),
 np.int64(654),
 np.int64(655),
 np.int64(656),
 np.int64(657),
 np.int64(658),
 np.int64(659),
 np.int64(660),
 np.int64(661),
 np.int64(662),
 np.int64(663),
 np.int64(664),
 np.int64(665),
 np.int64(666),
 np.int64(667),
 np.int64(668),
 np.int64(669),
 np.int64(670),
 np.int64(671),
 np.int64(672),
 np.int64(673),
 np.int64(674),
 np.int64(675),
 np.int64(676),
 np.int64(677),
 np.int64(678),
 np.int64(679),
 np.int64(680),
 np.int64(681),
 np.int64(682),
 np.int64(683),
 np.int64(684),
 np.int64(685),
 np.int64(686),
 np.int64(687),
 np.int64(688),
 np.int64(689),
 np.int64(690),
 np.int64(691),
 np.int64(692),
 np.int64(693),
 np.int64(694),
 np.int64(695),
 np.int64(696),
 np.int64(697),
 np.int64(698),
 np.int64(699),
 np.int64(700),
 np.int64(701),
 np.int64(702),
 np.int64(703),
 np.int64(704),
 np.int64(705),
 np.int64(706),
 np.int64(707),
 np.int64(708),
 np.int64(709),
 np.int64(710),
 np.int64(711),
 np.int64(712),
 np.int64(713),
 np.int64(714),
 np.int64(715),
 np.int64(716),
 np.int64(717),
 np.int64(718),
 np.int64(719),
 np.int64(720),
 np.int64(721),
 np.int64(722),
 np.int64(723),
 np.int64(724),
 np.int64(725),
 np.int64(726),
 np.int64(727),
 np.int64(728),
 np.int64(729),
 np.int64(730),
 np.int64(731),
 np.int64(732),
 np.int64(733),
 np.int64(734),
 np.int64(735),
 np.int64(736),
 np.int64(737),
 np.int64(738),
 np.int64(739),
 np.int64(740),
 np.int64(741),
 np.int64(742),
 np.int64(743),
 np.int64(744),
 np.int64(745),
 np.int64(746),
 np.int64(747),
 np.int64(748),
 np.int64(749),
 np.int64(750),
 np.int64(751),
 np.int64(752),
 np.int64(753),
 np.int64(754),
 np.int64(755),
 np.int64(756),
 np.int64(757),
 np.int64(758),
 np.int64(759),
 np.int64(760),
 np.int64(761),
 np.int64(762),
 np.int64(763),
 np.int64(764),
 np.int64(765),
 np.int64(766),
 np.int64(767),
 np.int64(768),
 np.int64(769),
 np.int64(770),
 np.int64(771),
 np.int64(772),
 np.int64(773),
 np.int64(774),
 np.int64(776),
 np.int64(777),
 np.int64(778),
 np.int64(779),
 np.int64(780),
 np.int64(781),
 np.int64(782),
 np.int64(783),
 np.int64(784),
 np.int64(785),
 np.int64(786),
 np.int64(787),
 np.int64(788),
 np.int64(789),
 np.int64(790),
 np.int64(791),
 np.int64(792),
 np.int64(793),
 np.int64(794),
 np.int64(795),
 np.int64(796),
 np.int64(797),
 np.int64(798),
 np.int64(799),
 np.int64(800),
 np.int64(801),
 np.int64(802),
 np.int64(803),
 np.int64(804),
 np.int64(805),
 np.int64(806),
 np.int64(807),
 np.int64(808),
 np.int64(809),
 np.int64(810),
 np.int64(811),
 np.int64(812),
 np.int64(813),
 np.int64(814),
 np.int64(815),
 np.int64(816),
 np.int64(817),
 np.int64(819),
 np.int64(820),
 np.int64(821),
 np.int64(822),
 np.int64(823),
 np.int64(824),
 np.int64(825),
 np.int64(826),
 np.int64(827),
 np.int64(828),
 np.int64(829),
 np.int64(830),
 np.int64(831),
 np.int64(832),
 np.int64(833),
 np.int64(834),
 np.int64(835),
 np.int64(836),
 np.int64(837),
 np.int64(838),
 np.int64(839),
 np.int64(840),
 np.int64(841),
 np.int64(842),
 np.int64(843),
 np.int64(844),
 np.int64(845),
 np.int64(847),
 np.int64(848),
 np.int64(849),
 np.int64(850),
 np.int64(851),
 np.int64(852),
 np.int64(853),
 np.int64(854),
 np.int64(855),
 np.int64(856),
 np.int64(857),
 np.int64(858),
 np.int64(859),
 np.int64(860),
 np.int64(861),
 np.int64(862),
 np.int64(863),
 np.int64(864),
 np.int64(865),
 np.int64(866),
 np.int64(867),
 np.int64(868),
 np.int64(869),
 np.int64(870),
 np.int64(871),
 np.int64(872),
 np.int64(873),
 np.int64(874),
 np.int64(875),
 np.int64(876),
 np.int64(877),
 np.int64(878),
 np.int64(879),
 np.int64(880),
 np.int64(881),
 np.int64(882),
 np.int64(883),
 np.int64(884),
 np.int64(885),
 np.int64(886),
 np.int64(887),
 np.int64(888),
 np.int64(889),
 np.int64(890),
 np.int64(891),
 np.int64(892),
 np.int64(893),
 np.int64(894),
 np.int64(895),
 np.int64(896),
 np.int64(897),
 np.int64(898),
 np.int64(899),
 np.int64(900),
 np.int64(901),
 np.int64(902),
 np.int64(903),
 np.int64(904),
 np.int64(905),
 np.int64(906),
 np.int64(907),
 np.int64(908),
 np.int64(909),
 np.int64(910),
 np.int64(911),
 np.int64(912),
 np.int64(913),
 np.int64(914),
 np.int64(915),
 np.int64(916),
 np.int64(917),
 np.int64(918),
 np.int64(919),
 np.int64(920),
 np.int64(921),
 np.int64(922),
 np.int64(923),
 np.int64(924),
 np.int64(926),
 np.int64(927),
 np.int64(928),
 np.int64(929),
 np.int64(930),
 np.int64(931),
 np.int64(932),
 np.int64(933),
 np.int64(934),
 np.int64(935),
 np.int64(936),
 np.int64(937),
 np.int64(938),
 np.int64(939),
 np.int64(940),
 np.int64(942),
 np.int64(943),
 np.int64(944),
 np.int64(945),
 np.int64(946),
 np.int64(947),
 np.int64(948),
 np.int64(949),
 np.int64(950),
 np.int64(951),
 np.int64(952),
 np.int64(953),
 np.int64(954),
 np.int64(955),
 np.int64(956),
 np.int64(957),
 np.int64(958),
 np.int64(959),
 np.int64(960),
 np.int64(961),
 np.int64(962),
 np.int64(963),
 np.int64(964),
 np.int64(965),
 np.int64(966),
 np.int64(967),
 np.int64(968),
 np.int64(969),
 np.int64(970),
 np.int64(971),
 np.int64(972),
 np.int64(973),
 np.int64(974),
 np.int64(976),
 np.int64(977),
 np.int64(978),
 np.int64(979),
 np.int64(980),
 np.int64(981),
 np.int64(982),
 np.int64(983),
 np.int64(984),
 np.int64(985),
 np.int64(986),
 np.int64(987),
 np.int64(988),
 np.int64(989),
 np.int64(990),
 np.int64(991),
 np.int64(992),
 np.int64(993),
 np.int64(994),
 np.int64(996),
 np.int64(997),
 np.int64(998),
 np.int64(999),
 np.int64(1000),
 np.int64(1001),
 np.int64(1002),
 np.int64(1003),
 np.int64(1004),
 np.int64(1005),
 np.int64(1006),
 np.int64(1007),
 np.int64(1008),
 np.int64(1009),
 np.int64(1010),
 np.int64(1011),
 np.int64(1012),
 np.int64(1013),
 np.int64(1014),
 np.int64(1015),
 np.int64(1016),
 np.int64(1017),
 np.int64(1018),
 np.int64(1019),
 np.int64(1020),
 np.int64(1021),
 np.int64(1022),
 np.int64(1023),
 np.int64(1024),
 np.int64(1025),
 np.int64(1026),
 np.int64(1027),
 np.int64(1028),
 np.int64(1029),
 np.int64(1030),
 np.int64(1031),
 np.int64(1032),
 np.int64(1033),
 np.int64(1034),
 np.int64(1035),
 np.int64(1036),
 np.int64(1037),
 ...]

,ID,IndexTrackObjectBegin,IndexTrackObjectEnd,IndexTrackEdgeBegin,IndexTrackEdgeEnd
0,1000000000,0,51,0,50
1,1000000001,51,155,50,153
2,1000000003,155,247,153,244
3,1000000004,247,361,244,357
4,1000000005,361,480,357,475
...,...,...,...,...,...
606,1000031677,31062,31064,30456,30457
607,1000031715,31064,31067,30457,30459
608,1000031744,31067,31070,30459,30461
609,1000031815,31070,31073,30461,30463
610,1000031961,31073,31075,30463,30464

In [ ]:
sorted(object_info["ID_Object"].unique())

[np.int64(0),
 np.int64(1),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9),
 np.int64(10),
 np.int64(11),
 np.int64(12),
 np.int64(13),
 np.int64(14),
 np.int64(15),
 np.int64(16),
 np.int64(17),
 np.int64(18),
 np.int64(19),
 np.int64(20),
 np.int64(21),
 np.int64(22),
 np.int64(23),
 np.int64(24),
 np.int64(25),
 np.int64(26),
 np.int64(29),
 np.int64(30),
 np.int64(31),
 np.int64(33),
 np.int64(34),
 np.int64(35),
 np.int64(36),
 np.int64(37),
 np.int64(38),
 np.int64(39),
 np.int64(40),
 np.int64(41),
 np.int64(42),
 np.int64(43),
 np.int64(44),
 np.int64(45),
 np.int64(47),
 np.int64(48),
 np.int64(49),
 np.int64(50),
 np.int64(51),
 np.int64(53),
 np.int64(54),
 np.int64(55),
 np.int64(56),
 np.int64(57),
 np.int64(58),
 np.int64(59),
 np.int64(60),
 np.int64(61),
 np.int64(62),
 np.int64(63),
 np.int64(64),
 np.int64(65),
 np.int64(66),
 np.int64(67),
 np.int64(68),
 np.int64(70),
 np.int64(71),
 np.int64(72),
 np.int64(73),
 np.int64(74),
 np.int64(75),
 np.int64(76),
 np.int64(77),
 np.int64(78),
 np.int64(79),
 np.int64(80),
 np.int64(81),
 np.int64(82),
 np.int64(83),
 np.int64(84),
 np.int64(85),
 np.int64(87),
 np.int64(88),
 np.int64(89),
 np.int64(90),
 np.int64(91),
 np.int64(92),
 np.int64(94),
 np.int64(95),
 np.int64(96),
 np.int64(97),
 np.int64(98),
 np.int64(99),
 np.int64(100),
 np.int64(101),
 np.int64(102),
 np.int64(103),
 np.int64(104),
 np.int64(105),
 np.int64(106),
 np.int64(107),
 np.int64(108),
 np.int64(109),
 np.int64(110),
 np.int64(111),
 np.int64(112),
 np.int64(113),
 np.int64(114),
 np.int64(115),
 np.int64(116),
 np.int64(117),
 np.int64(118),
 np.int64(119),
 np.int64(120),
 np.int64(121),
 np.int64(122),
 np.int64(123),
 np.int64(124),
 np.int64(125),
 np.int64(126),
 np.int64(127),
 np.int64(128),
 np.int64(129),
 np.int64(130),
 np.int64(131),
 np.int64(132),
 np.int64(133),
 np.int64(134),
 np.int64(135),
 np.int64(136),
 np.int64(137),
 np.int64(138),
 np.int64(139),
 np.int64(140),
 np.int64(141),
 np.int64(142),
 np.int64(143),
 np.int64(144),
 np.int64(145),
 np.int64(146),
 np.int64(147),
 np.int64(148),
 np.int64(149),
 np.int64(150),
 np.int64(152),
 np.int64(153),
 np.int64(154),
 np.int64(155),
 np.int64(156),
 np.int64(157),
 np.int64(158),
 np.int64(159),
 np.int64(161),
 np.int64(162),
 np.int64(163),
 np.int64(164),
 np.int64(165),
 np.int64(166),
 np.int64(167),
 np.int64(168),
 np.int64(169),
 np.int64(170),
 np.int64(171),
 np.int64(172),
 np.int64(173),
 np.int64(174),
 np.int64(175),
 np.int64(176),
 np.int64(177),
 np.int64(178),
 np.int64(179),
 np.int64(180),
 np.int64(181),
 np.int64(182),
 np.int64(183),
 np.int64(184),
 np.int64(185),
 np.int64(186),
 np.int64(187),
 np.int64(188),
 np.int64(189),
 np.int64(190),
 np.int64(191),
 np.int64(192),
 np.int64(193),
 np.int64(195),
 np.int64(196),
 np.int64(197),
 np.int64(198),
 np.int64(199),
 np.int64(200),
 np.int64(201),
 np.int64(202),
 np.int64(203),
 np.int64(204),
 np.int64(205),
 np.int64(206),
 np.int64(207),
 np.int64(208),
 np.int64(209),
 np.int64(211),
 np.int64(212),
 np.int64(213),
 np.int64(214),
 np.int64(215),
 np.int64(216),
 np.int64(218),
 np.int64(219),
 np.int64(220),
 np.int64(221),
 np.int64(222),
 np.int64(223),
 np.int64(224),
 np.int64(225),
 np.int64(226),
 np.int64(227),
 np.int64(228),
 np.int64(229),
 np.int64(231),
 np.int64(232),
 np.int64(233),
 np.int64(234),
 np.int64(235),
 np.int64(236),
 np.int64(237),
 np.int64(238),
 np.int64(239),
 np.int64(240),
 np.int64(241),
 np.int64(242),
 np.int64(244),
 np.int64(245),
 np.int64(246),
 np.int64(247),
 np.int64(248),
 np.int64(249),
 np.int64(251),
 np.int64(252),
 np.int64(253),
 np.int64(254),
 np.int64(255),
 np.int64(256),
 np.int64(257),
 np.int64(258),
 np.int64(259),
 np.int64(260),
 np.int64(261),
 np.int64(262),
 np.int64(263),
 np.int64(264),
 np.int64(265),
 np.int64(266),
 np.int64(267),
 np.int64(268),
 np.int64(269),
 np.int64(270),
 np.int64(271),
 np.int64(272),
 np.int64(273),
 np.int64(274),
 np.int64(275),
 np.int64(276),
 np.int64(277),
 np.int64(278),
 np.int64(279),
 np.int64(280),
 np.int64(281),
 np.int64(282),
 np.int64(283),
 np.int64(284),
 np.int64(285),
 np.int64(286),
 np.int64(287),
 np.int64(288),
 np.int64(289),
 np.int64(290),
 np.int64(291),
 np.int64(293),
 np.int64(294),
 np.int64(296),
 np.int64(297),
 np.int64(298),
 np.int64(299),
 np.int64(300),
 np.int64(301),
 np.int64(302),
 np.int64(304),
 np.int64(305),
 np.int64(306),
 np.int64(307),
 np.int64(308),
 np.int64(309),
 np.int64(310),
 np.int64(311),
 np.int64(313),
 np.int64(314),
 np.int64(315),
 np.int64(316),
 np.int64(317),
 np.int64(318),
 np.int64(319),
 np.int64(320),
 np.int64(321),
 np.int64(322),
 np.int64(323),
 np.int64(324),
 np.int64(325),
 np.int64(326),
 np.int64(327),
 np.int64(328),
 np.int64(329),
 np.int64(330),
 np.int64(331),
 np.int64(332),
 np.int64(333),
 np.int64(334),
 np.int64(336),
 np.int64(337),
 np.int64(338),
 np.int64(339),
 np.int64(340),
 np.int64(341),
 np.int64(342),
 np.int64(343),
 np.int64(344),
 np.int64(345),
 np.int64(346),
 np.int64(347),
 np.int64(348),
 np.int64(349),
 np.int64(350),
 np.int64(351),
 np.int64(352),
 np.int64(353),
 np.int64(355),
 np.int64(356),
 np.int64(357),
 np.int64(358),
 np.int64(360),
 np.int64(361),
 np.int64(362),
 np.int64(364),
 np.int64(365),
 np.int64(366),
 np.int64(367),
 np.int64(368),
 np.int64(369),
 np.int64(370),
 np.int64(371),
 np.int64(372),
 np.int64(373),
 np.int64(374),
 np.int64(375),
 np.int64(376),
 np.int64(377),
 np.int64(378),
 np.int64(379),
 np.int64(380),
 np.int64(381),
 np.int64(382),
 np.int64(383),
 np.int64(385),
 np.int64(386),
 np.int64(387),
 np.int64(388),
 np.int64(389),
 np.int64(390),
 np.int64(392),
 np.int64(393),
 np.int64(394),
 np.int64(395),
 np.int64(396),
 np.int64(397),
 np.int64(398),
 np.int64(399),
 np.int64(400),
 np.int64(401),
 np.int64(402),
 np.int64(403),
 np.int64(404),
 np.int64(405),
 np.int64(406),
 np.int64(407),
 np.int64(408),
 np.int64(409),
 np.int64(410),
 np.int64(411),
 np.int64(412),
 np.int64(413),
 np.int64(414),
 np.int64(415),
 np.int64(416),
 np.int64(417),
 np.int64(418),
 np.int64(419),
 np.int64(420),
 np.int64(421),
 np.int64(422),
 np.int64(423),
 np.int64(424),
 np.int64(425),
 np.int64(426),
 np.int64(427),
 np.int64(428),
 np.int64(429),
 np.int64(430),
 np.int64(431),
 np.int64(432),
 np.int64(433),
 np.int64(434),
 np.int64(435),
 np.int64(436),
 np.int64(437),
 np.int64(438),
 np.int64(439),
 np.int64(440),
 np.int64(441),
 np.int64(442),
 np.int64(443),
 np.int64(444),
 np.int64(446),
 np.int64(447),
 np.int64(448),
 np.int64(449),
 np.int64(450),
 np.int64(451),
 np.int64(452),
 np.int64(453),
 np.int64(454),
 np.int64(456),
 np.int64(457),
 np.int64(458),
 np.int64(459),
 np.int64(460),
 np.int64(461),
 np.int64(462),
 np.int64(463),
 np.int64(464),
 np.int64(465),
 np.int64(466),
 np.int64(467),
 np.int64(468),
 np.int64(469),
 np.int64(470),
 np.int64(471),
 np.int64(472),
 np.int64(473),
 np.int64(474),
 np.int64(475),
 np.int64(476),
 np.int64(477),
 np.int64(478),
 np.int64(479),
 np.int64(480),
 np.int64(481),
 np.int64(482),
 np.int64(483),
 np.int64(484),
 np.int64(485),
 np.int64(486),
 np.int64(487),
 np.int64(488),
 np.int64(489),
 np.int64(490),
 np.int64(491),
 np.int64(492),
 np.int64(493),
 np.int64(494),
 np.int64(495),
 np.int64(496),
 np.int64(497),
 np.int64(498),
 np.int64(499),
 np.int64(500),
 np.int64(501),
 np.int64(502),
 np.int64(503),
 np.int64(504),
 np.int64(506),
 np.int64(507),
 np.int64(508),
 np.int64(509),
 np.int64(510),
 np.int64(511),
 np.int64(512),
 np.int64(513),
 np.int64(514),
 np.int64(515),
 np.int64(516),
 np.int64(517),
 np.int64(518),
 np.int64(519),
 np.int64(520),
 np.int64(521),
 np.int64(522),
 np.int64(523),
 np.int64(524),
 np.int64(525),
 np.int64(526),
 np.int64(527),
 np.int64(528),
 np.int64(529),
 np.int64(530),
 np.int64(531),
 np.int64(532),
 np.int64(533),
 np.int64(534),
 np.int64(535),
 np.int64(536),
 np.int64(537),
 np.int64(538),
 np.int64(539),
 np.int64(540),
 np.int64(541),
 np.int64(542),
 np.int64(543),
 np.int64(544),
 np.int64(545),
 np.int64(546),
 np.int64(547),
 np.int64(548),
 np.int64(549),
 np.int64(550),
 np.int64(551),
 np.int64(552),
 np.int64(553),
 np.int64(554),
 np.int64(555),
 np.int64(556),
 np.int64(557),
 np.int64(558),
 np.int64(559),
 np.int64(560),
 np.int64(561),
 np.int64(562),
 np.int64(563),
 np.int64(564),
 np.int64(565),
 np.int64(566),
 np.int64(567),
 np.int64(568),
 np.int64(569),
 np.int64(570),
 np.int64(571),
 np.int64(572),
 np.int64(573),
 np.int64(574),
 np.int64(575),
 np.int64(576),
 np.int64(577),
 np.int64(578),
 np.int64(579),
 np.int64(580),
 np.int64(581),
 np.int64(582),
 np.int64(583),
 np.int64(584),
 np.int64(585),
 np.int64(586),
 np.int64(587),
 np.int64(588),
 np.int64(589),
 np.int64(590),
 np.int64(591),
 np.int64(592),
 np.int64(593),
 np.int64(594),
 np.int64(595),
 np.int64(597),
 np.int64(598),
 np.int64(599),
 np.int64(600),
 np.int64(601),
 np.int64(602),
 np.int64(603),
 np.int64(604),
 np.int64(605),
 np.int64(606),
 np.int64(607),
 np.int64(608),
 np.int64(609),
 np.int64(610),
 np.int64(611),
 np.int64(612),
 np.int64(613),
 np.int64(614),
 np.int64(615),
 np.int64(616),
 np.int64(617),
 np.int64(618),
 np.int64(619),
 np.int64(620),
 np.int64(621),
 np.int64(622),
 np.int64(623),
 np.int64(624),
 np.int64(625),
 np.int64(626),
 np.int64(627),
 np.int64(628),
 np.int64(629),
 np.int64(630),
 np.int64(631),
 np.int64(632),
 np.int64(633),
 np.int64(634),
 np.int64(635),
 np.int64(636),
 np.int64(637),
 np.int64(638),
 np.int64(639),
 np.int64(640),
 np.int64(641),
 np.int64(642),
 np.int64(643),
 np.int64(644),
 np.int64(645),
 np.int64(646),
 np.int64(647),
 np.int64(648),
 np.int64(649),
 np.int64(650),
 np.int64(651),
 np.int64(652),
 np.int64(653),
 np.int64(654),
 np.int64(655),
 np.int64(656),
 np.int64(657),
 np.int64(658),
 np.int64(659),
 np.int64(660),
 np.int64(661),
 np.int64(662),
 np.int64(663),
 np.int64(664),
 np.int64(665),
 np.int64(666),
 np.int64(667),
 np.int64(668),
 np.int64(669),
 np.int64(670),
 np.int64(671),
 np.int64(672),
 np.int64(673),
 np.int64(674),
 np.int64(675),
 np.int64(676),
 np.int64(677),
 np.int64(678),
 np.int64(679),
 np.int64(680),
 np.int64(681),
 np.int64(682),
 np.int64(683),
 np.int64(684),
 np.int64(685),
 np.int64(686),
 np.int64(687),
 np.int64(688),
 np.int64(689),
 np.int64(690),
 np.int64(691),
 np.int64(692),
 np.int64(693),
 np.int64(694),
 np.int64(695),
 np.int64(696),
 np.int64(697),
 np.int64(698),
 np.int64(699),
 np.int64(700),
 np.int64(701),
 np.int64(702),
 np.int64(703),
 np.int64(704),
 np.int64(705),
 np.int64(706),
 np.int64(707),
 np.int64(708),
 np.int64(709),
 np.int64(710),
 np.int64(711),
 np.int64(712),
 np.int64(713),
 np.int64(714),
 np.int64(715),
 np.int64(716),
 np.int64(717),
 np.int64(718),
 np.int64(719),
 np.int64(720),
 np.int64(721),
 np.int64(722),
 np.int64(723),
 np.int64(724),
 np.int64(725),
 np.int64(726),
 np.int64(727),
 np.int64(728),
 np.int64(729),
 np.int64(730),
 np.int64(731),
 np.int64(732),
 np.int64(733),
 np.int64(734),
 np.int64(735),
 np.int64(736),
 np.int64(737),
 np.int64(738),
 np.int64(739),
 np.int64(740),
 np.int64(741),
 np.int64(742),
 np.int64(743),
 np.int64(744),
 np.int64(745),
 np.int64(746),
 np.int64(747),
 np.int64(748),
 np.int64(749),
 np.int64(750),
 np.int64(751),
 np.int64(752),
 np.int64(753),
 np.int64(754),
 np.int64(755),
 np.int64(756),
 np.int64(757),
 np.int64(758),
 np.int64(759),
 np.int64(760),
 np.int64(761),
 np.int64(762),
 np.int64(763),
 np.int64(764),
 np.int64(765),
 np.int64(766),
 np.int64(767),
 np.int64(768),
 np.int64(769),
 np.int64(770),
 np.int64(771),
 np.int64(772),
 np.int64(773),
 np.int64(774),
 np.int64(776),
 np.int64(777),
 np.int64(778),
 np.int64(779),
 np.int64(780),
 np.int64(781),
 np.int64(782),
 np.int64(783),
 np.int64(784),
 np.int64(785),
 np.int64(786),
 np.int64(787),
 np.int64(788),
 np.int64(789),
 np.int64(790),
 np.int64(791),
 np.int64(792),
 np.int64(793),
 np.int64(794),
 np.int64(795),
 np.int64(796),
 np.int64(797),
 np.int64(798),
 np.int64(799),
 np.int64(800),
 np.int64(801),
 np.int64(802),
 np.int64(803),
 np.int64(804),
 np.int64(805),
 np.int64(806),
 np.int64(807),
 np.int64(808),
 np.int64(809),
 np.int64(810),
 np.int64(811),
 np.int64(812),
 np.int64(813),
 np.int64(814),
 np.int64(815),
 np.int64(816),
 np.int64(817),
 np.int64(819),
 np.int64(820),
 np.int64(821),
 np.int64(822),
 np.int64(823),
 np.int64(824),
 np.int64(825),
 np.int64(826),
 np.int64(827),
 np.int64(828),
 np.int64(829),
 np.int64(830),
 np.int64(831),
 np.int64(832),
 np.int64(833),
 np.int64(834),
 np.int64(835),
 np.int64(836),
 np.int64(837),
 np.int64(838),
 np.int64(839),
 np.int64(840),
 np.int64(841),
 np.int64(842),
 np.int64(843),
 np.int64(844),
 np.int64(845),
 np.int64(847),
 np.int64(848),
 np.int64(849),
 np.int64(850),
 np.int64(851),
 np.int64(852),
 np.int64(853),
 np.int64(854),
 np.int64(855),
 np.int64(856),
 np.int64(857),
 np.int64(858),
 np.int64(859),
 np.int64(860),
 np.int64(861),
 np.int64(862),
 np.int64(863),
 np.int64(864),
 np.int64(865),
 np.int64(866),
 np.int64(867),
 np.int64(868),
 np.int64(869),
 np.int64(870),
 np.int64(871),
 np.int64(872),
 np.int64(873),
 np.int64(874),
 np.int64(875),
 np.int64(876),
 np.int64(877),
 np.int64(878),
 np.int64(879),
 np.int64(880),
 np.int64(881),
 np.int64(882),
 np.int64(883),
 np.int64(884),
 np.int64(885),
 np.int64(886),
 np.int64(887),
 np.int64(888),
 np.int64(889),
 np.int64(890),
 np.int64(891),
 np.int64(892),
 np.int64(893),
 np.int64(894),
 np.int64(895),
 np.int64(896),
 np.int64(897),
 np.int64(898),
 np.int64(899),
 np.int64(900),
 np.int64(901),
 np.int64(902),
 np.int64(903),
 np.int64(904),
 np.int64(905),
 np.int64(906),
 np.int64(907),
 np.int64(908),
 np.int64(909),
 np.int64(910),
 np.int64(911),
 np.int64(912),
 np.int64(913),
 np.int64(914),
 np.int64(915),
 np.int64(916),
 np.int64(917),
 np.int64(918),
 np.int64(919),
 np.int64(920),
 np.int64(921),
 np.int64(922),
 np.int64(923),
 np.int64(924),
 np.int64(926),
 np.int64(927),
 np.int64(928),
 np.int64(929),
 np.int64(930),
 np.int64(931),
 np.int64(932),
 np.int64(933),
 np.int64(934),
 np.int64(935),
 np.int64(936),
 np.int64(937),
 np.int64(938),
 np.int64(939),
 np.int64(940),
 np.int64(942),
 np.int64(943),
 np.int64(944),
 np.int64(945),
 np.int64(946),
 np.int64(947),
 np.int64(948),
 np.int64(949),
 np.int64(950),
 np.int64(951),
 np.int64(952),
 np.int64(953),
 np.int64(954),
 np.int64(955),
 np.int64(956),
 np.int64(957),
 np.int64(958),
 np.int64(959),
 np.int64(960),
 np.int64(961),
 np.int64(962),
 np.int64(963),
 np.int64(964),
 np.int64(965),
 np.int64(966),
 np.int64(967),
 np.int64(968),
 np.int64(969),
 np.int64(970),
 np.int64(971),
 np.int64(972),
 np.int64(973),
 np.int64(974),
 np.int64(976),
 np.int64(977),
 np.int64(978),
 np.int64(979),
 np.int64(980),
 np.int64(981),
 np.int64(982),
 np.int64(983),
 np.int64(984),
 np.int64(985),
 np.int64(986),
 np.int64(987),
 np.int64(988),
 np.int64(989),
 np.int64(990),
 np.int64(991),
 np.int64(992),
 np.int64(993),
 np.int64(994),
 np.int64(996),
 np.int64(997),
 np.int64(998),
 np.int64(999),
 np.int64(1000),
 np.int64(1001),
 np.int64(1002),
 np.int64(1003),
 np.int64(1004),
 np.int64(1005),
 np.int64(1006),
 np.int64(1007),
 np.int64(1008),
 np.int64(1009),
 np.int64(1010),
 np.int64(1011),
 np.int64(1012),
 np.int64(1013),
 np.int64(1014),
 np.int64(1015),
 np.int64(1016),
 np.int64(1017),
 np.int64(1018),
 np.int64(1019),
 np.int64(1020),
 np.int64(1021),
 np.int64(1022),
 np.int64(1023),
 np.int64(1024),
 np.int64(1025),
 np.int64(1026),
 np.int64(1027),
 np.int64(1028),
 np.int64(1029),
 np.int64(1030),
 np.int64(1031),
 np.int64(1032),
 np.int64(1033),
 np.int64(1034),
 np.int64(1035),
 np.int64(1036),
 np.int64(1037),
 ...]

In [39]:
object_info

       ID_Object
0              0
1            351
2            547
3            808
4           1074
...          ...
31070      31815
31071      32081
31072      32346
31073      31961
31074      32213

[31075 rows x 1 columns]

In [46]:
sorted(object_info[0:51]['ID_Object'])

[0,
 351,
 547,
 808,
 1074,
 1338,
 1610,
 1893,
 2156,
 2431,
 2697,
 2980,
 3325,
 3588,
 3789,
 4057,
 4328,
 4607,
 4881,
 5166,
 5509,
 5704,
 5972,
 6249,
 6526,
 6805,
 7078,
 7342,
 7624,
 7901,
 8253,
 8450,
 8798,
 8999,
 9357,
 9626,
 9899,
 10097,
 10386,
 10667,
 11005,
 11214,
 11486,
 11760,
 12039,
 12583,
 12857,
 13126,
 13393,
 13658,
 13919]