In [11]:
import os
import ray
import numpy as np
import pandas as pd
from typing import List
from utils.data import load_yaml
from imaris.imaris import ImarisDataObject

In [12]:
ims_file = "/home/shehan/Documents/projects/nih/nih_parsers/data/spots/Day2 RFL Gran2 3x3 2h_[ii9_TileScan_003_Merging001_Image_10].ims"
ims_object = ImarisDataObject(ims_file)
data = ims_object.data

Imaris Object

In [13]:
# get all the points available
ims_object.get_object_names("Points")

index = "Points0"

In [14]:
# get all the available statistics names
ims_object.get_stats_names(index)

        ID  ID_Category  ID_FactorList          Name       Unit
0     7621            0              0  Acceleration  b'um/s^2'
1     7621            0              0  Acceleration  b'um/s^2'
2     7621            0              0  Acceleration  b'um/s^2'
3     7621            0              0  Acceleration  b'um/s^2'
4     7621            0              0  Acceleration  b'um/s^2'
...    ...          ...            ...           ...        ...
5091  7744            0              0        Volume    b'um^3'
5092  7744            0              0        Volume    b'um^3'
5093  7744            0              0        Volume    b'um^3'
5094  7744            0              0        Volume    b'um^3'
5095  7744            0              0        Volume    b'um^3'

[5096 rows x 5 columns]

In [15]:
# get all the statistics values
ims_object.get_stats_values(index)

          ID_Time   ID_Object  ID_StatisticsType          Value
0              -1          -1                  2   16675.000000
1              -1          -1                  3  274649.000000
2              -1  1000001241               7682      -0.548451
3              -1  1000001818               7682      -0.410397
4              -1  1000001927               7682      -0.146257
...           ...         ...                ...            ...
20475925       68     4949633               7744     402.123871
20475926       68     4949641               7744     402.123871
20475927       68     4949683               7744     402.123871
20475928       68     4949696               7744     402.123871
20475929       68     4949703               7744     402.123871

[20475930 rows x 4 columns]

In [16]:
# get all the track information
ims_object.get_track_ids(index)

0        1000001241
1        1000001818
2        1000001927
3        1000001973
4        1000002021
            ...
16670    1004945574
16671    1004945595
16672    1004945636
16673    1004945736
16674    1004945765
Name: ID, Length: 16675, dtype: int64

In [17]:
# get track information
ims_object.get_track_info(index)

,ID,IndexTrackObjectBegin,IndexTrackObjectEnd,IndexTrackEdgeBegin,IndexTrackEdgeEnd
0,1000001241,0,69,0,68
1,1000001818,69,74,68,72
2,1000001927,74,82,72,79
3,1000001973,82,116,79,112
4,1000002021,116,185,112,180
...,...,...,...,...,...
16670,1004945574,263223,263225,246553,246554
16671,1004945595,263225,263227,246554,246555
16672,1004945636,263227,263229,246555,246556
16673,1004945736,263229,263231,246556,246557
16674,1004945765,263231,263233,246557,246558

In [18]:
# get object id information
ims_object.get_track_object_info(index)

0            1241
1           70935
2         4682501
3         4686448
4         4690390
           ...
263228    4949575
263229    4945736
263230    4949682
263231    4945765
263232    4949706
Name: ID_Object, Length: 263233, dtype: int64

In [19]:
ims_object.get_track_object_info(index)

0            1241
1           70935
2         4682501
3         4686448
4         4690390
           ...
263228    4949575
263229    4945736
263230    4949682
263231    4945765
263232    4949706
Name: ID_Object, Length: 263233, dtype: int64

Looking Directly Into The File

In [20]:
ims_object.data.get("Scene8").get("Content").keys()

In [21]:
list(ims_object.data.get("Scene8").get("Content").get("Points0").keys())

['Category',
 'CreationParameters',
 'Factor',
 'FactorList',
 'LabelColor',
 'LabelColorData',
 'LabelColorLabelGroupNames',
 'LabelColorLabelValues',
 'LabelGroupNames',
 'LabelSetLabelIDs',
 'LabelSetObjectIDs',
 'LabelSets',
 'LabelValues',
 'MainTrackSegmentTable',
 'MainTrackSegmentTable_Focus',
 'MainTrackTable',
 'Spot',
 'SpotTimeOffset',
 'StatisticsType',
 'StatisticsValue',
 'StatisticsValueTimeOffset',
 'Time',
 'TimeBegin',
 'Track0',
 'TrackEdge0',
 'TrackObject0',
 'TrackSegment0',
 'TrackSegment0_Focus']

In [22]:
list(ims_object.data.get("Scene8").get("Content").get("Points4").keys())

['Category',
 'CreationParameters',
 'Factor',
 'FactorList',
 'LabelColor',
 'LabelColorData',
 'LabelColorLabelGroupNames',
 'LabelColorLabelValues',
 'LabelGroupNames',
 'LabelSetLabelIDs',
 'LabelSetObjectIDs',
 'LabelSets',
 'LabelValues',
 'MainTrackSegmentTable',
 'MainTrackSegmentTable_Focus',
 'MainTrackTable',
 'Spot',
 'SpotTimeOffset',
 'StatisticsType',
 'StatisticsValue',
 'StatisticsValueTimeOffset',
 'Time',
 'TimeBegin',
 'Track0',
 'TrackEdge0',
 'TrackObject0',
 'TrackSegment0',
 'TrackSegment0_Focus']

In [23]:
ims_object.data.get("Scene8").get("Content").get("Points0").get("Track0")

In [24]:
ims_object.data.get("Scene8").get("Content").get("Points0").get("TrackObject0")

In [25]:
ims_object.data.get("Scene8").get("Content").get("Points0").get("StatisticsValue")

Track Information

In [26]:
np.array(ims_object.data.get("Scene8").get("Content").get("Points0").get("Track0"))

array([(1000001241,      0,     69,      0,     68),
       (1000001818,     69,     74,     68,     72),
       (1000001927,     74,     82,     72,     79), ...,
       (1004945636, 263227, 263229, 246555, 246556),
       (1004945736, 263229, 263231, 246556, 246557),
       (1004945765, 263231, 263233, 246557, 246558)],
      dtype=[('ID', '<i8'), ('IndexTrackObjectBegin', '<i8'), ('IndexTrackObjectEnd', '<i8'), ('IndexTrackEdgeBegin', '<i8'), ('IndexTrackEdgeEnd', '<i8')])

In [27]:
np.array(ims_object.data.get("Scene8").get("Content").get("Points0").get("TrackObject0"))

array([(   1241,), (  70935,), (4682501,), ..., (4949682,), (4945765,),
       (4949706,)], dtype=[('ID_Object', '<i8')])

In [28]:
np.array(ims_object.data.get("Scene8").get("Content").get("Points0").get("TrackObject0")).shape

(263233,)