In [2]:
import os
import ray
import numpy as np
import pandas as pd
from typing import List
from utils.data import load_yaml
from imaris.imaris import ImarisDataObject
from parsers.filament_parser import FilamentParserDistributed
import time

In [3]:
# ims_file = "/home/shehan/Documents/projects/nih/nih_parsers/data/temp_test/Ex112-mitotrackerred-B6-BALB-050125_batch_TileScan_1_BALB-US-Position_3_(0).ims"
ims_file = "/home/shehan/Documents/projects/nih/nih_parsers/data/filaments/NeuronDemo_with_objects.ims"
parser = FilamentParserDistributed(ims_file_path=ims_file)
ims = ImarisDataObject(ims_file)
data = ims.data
ims.get_object_names("Filament")

['Filaments0', 'Filaments1']

In [4]:
out = parser.inspect(0)

In [6]:
f = out["final_df"]
f2 = out["final_df2"]
f.equals(f2)

True

In [7]:
f

,Filament Area (sum),Filament BoundingBoxAA Length X,Filament BoundingBoxAA Length Y,Filament BoundingBoxAA Length Z,Filament BoundingBoxOO Length A,Filament BoundingBoxOO Length B,Filament BoundingBoxOO Length C,Filament Distance from Origin,Filament Full Branch Depth,Filament Full Branch Level,...,Spine Terminal Pt Position X Depth_10 Level_5,Spine Terminal Pt Position Y Depth_10 Level_5,Spine Terminal Pt Position Z Depth_10 Level_5,Spine Terminal Pt Time Depth_10 Level_5,Spine Terminal Pt Time Index Depth_10 Level_5,Spine Terminal Pt Volume Depth_10 Level_5,Spine Time Depth_10 Level_5,Spine Time Index Depth_10 Level_5,Spine Volume Depth_10 Level_5,Object_ID
100000000,34922.445312,319.091064,302.782532,71.871277,70.432693,308.026825,323.984497,246.780273,10.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100000000
800000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,800000000
800000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,800000001
800000002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,800000002
800000003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,800000003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
610000017839,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,610000017839
610000017842,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,610000017842
610000017844,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,610000017844
610000017846,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,610000017846
610000017848,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,610000017848

In [7]:
list(data.get("Scene8").get("Content").get("Filaments0").keys())

['Category',
 'DendriteSegment',
 'DendriteSegmentEdge',
 'DendriteSegmentTimeOffset',
 'DendriteSegmentVertex',
 'Edge',
 'EdgeTimeOffset',
 'Factor',
 'FactorList',
 'Filament',
 'FilamentTimeOffset',
 'LabelColor',
 'LabelColorData',
 'LabelColorLabelGroupNames',
 'LabelColorLabelValues',
 'LabelGroupNames',
 'LabelSetLabelIDs',
 'LabelSetObjectIDs',
 'LabelSets',
 'LabelValues',
 'MainTrackSegmentTable',
 'MainTrackSegmentTable_Focus',
 'Points',
 'Soma',
 'SomaTable',
 'Spine',
 'SpineEdge',
 'SpineTimeOffset',
 'SpineVertex',
 'StatisticsType',
 'StatisticsValue',
 'StatisticsValueTimeOffset',
 'Time',
 'TimeBegin',
 'TrackSegment0',
 'TrackSegment0_Focus',
 'Vertex',
 'VertexTimeOffset']

In [ ]:
stats_values = pd.DataFrame(
    np.asarray(
        data.get("Scene8").get("Content").get("Filaments0").get("StatisticsValue")
    )
)
stats_values

        ID_Time     ID_Object  ID_StatisticsType         Value
0            -1            -1                 39      0.000000
1            -1            -1                 40      1.000000
2            -1            -1                 42      0.000000
3            -1            -1                 43   2756.000000
4             0     100000000              14498  34922.445312
...         ...           ...                ...           ...
172601        0  610000012326              38075      0.539114
172602        0  610000013367              38075      0.279294
172603        0  610000014967              38075      1.133404
172604        0  610000016149              38075     10.039692
172605        0  610000017286              38075      0.895864

[172606 rows x 4 columns]

In [15]:
np.array(data.get("Scene8").get("Content").get("Filaments0").get("TrackSegment0"))

array([(0, 100000000, 0.)],
      dtype=[('ID', '<i8'), ('FirstObjectId', '<i8'), ('Position', '<f8')])

In [ ]:
object_ids = pd.DataFrame(
    np.asarray(
        data.get("Scene8").get("Content").get("MegaSurfaces0").get("TrackObject0")
    )
)
object_ids

In [ ]:
object_ids = pd.DataFrame(
    np.asarray(
        data.get("Scene8").get("Content").get("MegaSurfaces0").get("SurfaceModel")
    )
)
object_ids

In [ ]:
trackinfo = pd.DataFrame(
    np.asarray(data.get("Scene8").get("Content").get("MegaSurfaces0").get("Track0"))
)
trackinfo

In [ ]:
segments = pd.DataFrame(
    np.asarray(data.get("Scene8").get("Content").get("MegaSurfaces0").get("TrackEdge0"))
)
segments

In [ ]:
TrackSegment0

In [ ]:
out = parser.inspect(0)

In [ ]:
f = out["stats_df"]
f2 = out["stats_df2"]
f.equals(f2)